"""
vools.bridge.typescript.compiler - TypeScript/JavaScript 语言桥接编译器实现

提供 TypeScriptBridge 类，继承 LangBridge 抽象基类，实现 TypeScript 特定的
代码生成、编译（TS -> JS）和调用逻辑（通过 Node.js 子进程）。
"""

import os
import sys
import json
import shutil
import hashlib
import tempfile
import subprocess
import platform
import inspect
from pathlib import Path
from typing import Any, Dict, List, Optional, Callable
from concurrent.futures import ThreadPoolExecutor, Future
from ...core.dataclass_compat import dataclass

from .._base import LangBridge, FunctionSpec, FunctionParser
from ..core.types import LangType

# 平台判断
_IS_WINDOWS = platform.system() == 'Windows'
_IS_LINUX = platform.system() == 'Linux'
_IS_MACOS = platform.system() == 'Darwin'

# 缓存目录
_TS_CACHE_DIR = Path(tempfile.gettempdir()) / 'vools_ts_cache'
_TS_CACHE_DIR.mkdir(parents=True, exist_ok=True)

# ============================================================================
# 类型映射
# ============================================================================

PY_TO_TS_TYPE = {
    int: 'number',
    float: 'number',
    str: 'string',
    bool: 'boolean',
    list: 'any[]',
    dict: 'Record<string, any>',
    type(None): 'null',
}

TS_TO_PY_TYPE = {
    'number': (int, float),
    'string': str,
    'boolean': bool,
    'any[]': list,
    'Record<string, any>': dict,
    'null': type(None),
}


def get_ts_type(py_type: type) -> str:
    """Python 类型 -> TypeScript 类型"""
    return PY_TO_TS_TYPE.get(py_type, 'any')


# ============================================================================
# 编译器检测
# ============================================================================

def is_node_available() -> bool:
    """检测 node 是否可用"""
    return shutil.which('node') is not None


def is_typescript_available() -> bool:
    """检测 tsc 是否可用"""
    return shutil.which('tsc') is not None or shutil.which('npx') is not None


def ts_compiler_available() -> bool:
    """TypeScript 桥接是否完全可用（需要 node + tsc）"""
    return is_node_available()


def get_node_version() -> Optional[str]:
    """获取 Node.js 版本"""
    node = shutil.which('node')
    if not node:
        return None
    try:
        result = subprocess.run(
            [node, '--version'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True,
            timeout=5,
        )
        return result.stdout.strip() or None
    except Exception:
        return None


def get_tsc_version() -> Optional[str]:
    """获取 TypeScript 编译器版本"""
    tsc = shutil.which('tsc')
    if not tsc:
        return None
    try:
        result = subprocess.run(
            [tsc, '--version'],
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True,
            timeout=5,
        )
        return result.stdout.strip() or None
    except Exception:
        return None


# ============================================================================
# 代码生成
# ============================================================================

TS_FUNCTION_TEMPLATE = '''// Auto-generated by vools.bridge.typescript
// Source hash: {hash}

function {func_name}({param_list}) {{
    {user_code}
}}

// Main entry point
async function __vools_main(args) {{
    const params = {param_names};
    const userFn = {func_name};

    // Call with positional args
    if (params.length === 0) {{
        return await userFn();
    }} else if (params.length === 1) {{
        return await userFn(args[0]);
    }} else {{
        return await userFn.apply(null, args);
    }}
}}

// CLI entry
if (require.main === module) {{
    let input = '';
    process.stdin.setEncoding('utf-8');
    process.stdin.on('data', (chunk) => {{ input += chunk; }});
    process.stdin.on('end', async () => {{
        let okFlag = true;
        let resultValue = null;
        let errMsg = '';
        let errStack = '';
        try {{
            const data = JSON.parse(input);
            const args = data.args || [];
            resultValue = await __vools_main(args);
        }} catch (err) {{
            okFlag = false;
            errMsg = err && err.message ? err.message : String(err);
            errStack = err && err.stack ? err.stack : '';
        }}
        const outPayload = {{ ok: okFlag, result: resultValue, error: errMsg, stack: errStack }};
        process.stdout.write(JSON.stringify(outPayload));
    }});
}}
'''


def _generate_ts_source(user_code: str, func_name: str, param_names: List[str]) -> str:
    """生成 TypeScript 源码"""
    code_hash = hashlib.md5(user_code.encode()).hexdigest()[:12]
    return TS_FUNCTION_TEMPLATE.format(
        hash=code_hash,
        user_code=user_code,
        func_name=func_name,
        param_list=', '.join(param_names),
        param_names=json.dumps(param_names),
    )


# ============================================================================
# 编译
# ============================================================================

def _compile_ts_code(source: str, cache_key: str) -> Path:
    """
    编译 TypeScript 源码为 JavaScript
    返回 JS 文件路径

    注意：直接输出 JS，不使用 tsc。
    TypeScript 类型注解由 _strip_typescript() 去除。
    这种方式更简单可靠，避免 tsc 5+ 的简写优化破坏对象字面量。
    """
    cache_subdir = _TS_CACHE_DIR / cache_key
    cache_subdir.mkdir(parents=True, exist_ok=True)

    ts_file = cache_subdir / 'main.ts'
    js_file = cache_subdir / 'main.js'

    ts_file.write_text(source, encoding='utf-8')

    # 直接将 TS 转为 JS（去除类型注解）
    js_content = _strip_typescript(source)
    js_file.write_text(js_content, encoding='utf-8')

    return js_file


def _strip_typescript(source: str) -> str:
    """简单去除 TypeScript 类型注解（作为 tsc 不可用时的回退）"""
    import re
    lines = source.split('\n')
    out_lines = []
    for line in lines:
        # 跳过 TS 特定的语法
        stripped = line
        # interface / type alias / declare 整行删除
        if re.match(r'^\s*(interface|type\s+\w+\s*=)\s', stripped):
            continue
        # 函数返回类型: function fn(): number { -> function fn() {
        stripped = re.sub(r'\)\s*:\s*[A-Za-z_<>|][\w<>|,\s\[\]\?]*\s*(\{)', r') \1', stripped)
        # 函数返回类型(箭头函数): const fn = (): number =>  -> const fn = () =>
        stripped = re.sub(r'\)\s*:\s*[A-Za-z_<>|][\w<>|,\s\[\]\?]*\s*(=>)', r') \1', stripped)
        # 函数参数类型(箭头函数): (x: number, y: string) =>  -> (x, y) =>
        # 注意：要避开对象字面量的 key: value 形式
        if '=>' in stripped and not re.search(r'^\s*[a-zA-Z_]+\s*:', stripped):
            stripped = re.sub(r':\s*[A-Za-z_<>|][\w<>|,\s\[\]\?]*?(?=[,)])', '', stripped)
        # 变量类型注解: const x: number = 5 -> const x = 5
        # 但不能破坏对象字面量 {key: value}
        stripped = re.sub(r'(?<=[\s,;\(])\b([a-zA-Z_]\w*)\s*:\s*[A-Za-z_<>|][\w<>|,\s\[\]\?]*\s*(?==)', r'\1', stripped)
        # 参数类型: function add(a: int, b: int) -> function add(a, b)
        # 只在函数定义上下文中
        if re.search(r'\bfunction\s+\w+\s*\(', stripped) or re.search(r'\b\w+\s*=\s*\(', stripped):
            stripped = re.sub(r':\s*[A-Za-z_<>|][\w<>|,\s\[\]\?]*?(?=[,)])', '', stripped)
        out_lines.append(stripped)
    return '\n'.join(out_lines)


# ============================================================================
# 函数调用
# ============================================================================

def _call_ts_function(js_file: Path, args: List[Any]) -> Any:
    """通过 Node.js 子进程执行 JS 并返回结果"""
    node = shutil.which('node')
    if not node:
        raise RuntimeError('Node.js 不可用，无法执行 TypeScript 桥接')

    payload = json.dumps({'args': args}, ensure_ascii=False)

    try:
        result = subprocess.run(
            [node, str(js_file)],
            input=payload,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True,
            timeout=30,
        )

        output = result.stdout.strip()
        if not output:
            raise RuntimeError(f'Node.js 无输出: stderr={result.stderr}')

        data = json.loads(output)
        if not data.get('ok'):
            raise RuntimeError(f'TS 执行失败: {data.get("error")}\n{data.get("stack", "")}')

        return data.get('result')
    except subprocess.TimeoutExpired:
        raise RuntimeError('TS 执行超时（>30s）')
    except json.JSONDecodeError as e:
        raise RuntimeError(f'TS 输出无法解析为 JSON: {e}\n输出: {output[:500]}')


# ============================================================================
# 异步 Future
# ============================================================================

class TSFuture:
    """TypeScript 异步执行 Future"""

    def __init__(self, executor: ThreadPoolExecutor, js_file: Path, args: List[Any]):
        self._executor = executor
        self._js_file = js_file
        self._args = args
        self._future: Future = executor.submit(_call_ts_function, js_file, args)

    def result(self, timeout: Optional[float] = None) -> Any:
        return self._future.result(timeout=timeout)

    def __await__(self):
        # 用线程池包装实现 await
        import asyncio
        loop = asyncio.get_event_loop()
        return loop.run_in_executor(None, self._future.result).__await__()


# ============================================================================
# 桥接装饰器（在 _ts_bridge 定义后赋值）
# ============================================================================


def compile_and_run(source: str, func_name: str, param_names: List[str], args: List[Any]) -> Any:
    """便捷入口：直接编译运行"""
    src = _generate_ts_source(source, func_name, param_names)
    cache_key = hashlib.md5(src.encode()).hexdigest()[:16]
    js_file = _compile_ts_code(src, cache_key)
    return _call_ts_function(js_file, args)


# ============================================================================
# Bridge 类
# ============================================================================

class TypeScriptBridge(LangBridge):
    """TypeScript/JavaScript 语言桥接实现。

    通过 Node.js 子进程执行编译后的 JS 代码，使用 JSON 序列化进行数据交换。
    支持 TypeScript 和纯 JavaScript。

    Attributes:
        name: 语言名称 'typescript'。
        file_ext: 源文件扩展名 '.ts'。
        lib_ext: 编译产物扩展名 '.js'。
        _executor: 异步执行线程池。
    """

    name = 'typescript'
    is_compiled = False
    lang_type = LangType.INTERPRETED
    file_ext = '.ts'
    lib_ext = '.js'

    def __init__(self):
        """初始化 TypeScriptBridge 实例。"""
        super().__init__()
        self._executor = ThreadPoolExecutor(
            max_workers=4, thread_name_prefix='ts-bridge'
        )

    def default_cache_dir(self) -> str:
        """默认缓存目录路径。

        Returns:
            str: 默认缓存目录的绝对路径。
        """
        return str(_TS_CACHE_DIR)

    def compiler_available(self) -> bool:
        """检查 TypeScript 运行环境是否可用（需要 Node.js）。

        Returns:
            bool: Node.js 可用时返回 True，否则返回 False。
        """
        return ts_compiler_available()

    def _execute_code(self, package_path, func_name, args, ret_type=None):
        """解包并执行代码。"""
        import zipfile, tempfile, os, shutil
        from pathlib import Path

        tmpdir = tempfile.mkdtemp()
        try:
            with zipfile.ZipFile(package_path, 'r') as zf:
                zf.extractall(tmpdir)

            source_file = os.path.join(tmpdir, self.get_source_filename(func_name))
            source = Path(source_file).read_text(encoding='utf-8')

            # Compile TS to JS and write to temp file
            js_content = _strip_typescript(source)
            js_file = os.path.join(tmpdir, 'main.js')
            Path(js_file).write_text(js_content, encoding='utf-8')

            # Execute via stdin/stdout protocol
            return _call_ts_function(Path(js_file), list(args))
        finally:
            shutil.rmtree(tmpdir, ignore_errors=True)

    def generate_code(self, spec: FunctionSpec) -> str:
        """根据函数规格生成 TypeScript 源码。

        支持两种函数体提取方式：
        1. 优先使用 spec.body（return 字符串方式，与其他语言一致）
        2. fallback 到函数的 __doc__（旧版兼容方式）

        Args:
            spec: 函数规格对象，包含函数名、参数、函数体等信息。

        Returns:
            str: 生成的完整 TypeScript 源码（含入口模板）。
        """
        parts = []

        # 1. module_code（放在最前面，用于 import 语句、类型定义等）
        if spec.module_code:
            parts.append(spec.module_code)

        # 2. 依赖函数（递归生成每个依赖函数的 TypeScript 代码）
        for dep in spec.dependencies:
            dep_code = self.generate_code(dep)
            parts.append(dep_code)

        # 3. 主函数
        user_code = spec.body or ''
        func_name = spec.name
        param_names = list(spec.annotations.keys()) if spec.annotations else []
        if 'return' in param_names:
            param_names.remove('return')
        parts.append(_generate_ts_source(user_code, func_name, param_names))

        return '\n\n'.join(parts)

    def compile_code(self, code: str, func_name: str, cache_dir: Optional[str] = None) -> str:
        """编译 TypeScript 代码为 JavaScript 文件。

        Args:
            code: TypeScript 源代码字符串。
            func_name: 函数名称（用于缓存标识）。
            cache_dir: 自定义缓存目录，为 None 时使用默认目录。

        Returns:
            str: 编译后的 JS 文件路径。
        """
        cache_key = hashlib.md5(code.encode()).hexdigest()[:16]
        if cache_dir:
            cache_subdir = Path(cache_dir) / cache_key
            cache_subdir.mkdir(parents=True, exist_ok=True)
            ts_file = cache_subdir / 'main.ts'
            js_file = cache_subdir / 'main.js'
            ts_file.write_text(code, encoding='utf-8')
            js_content = _strip_typescript(code)
            js_file.write_text(js_content, encoding='utf-8')
            return str(js_file)
        js_file = _compile_ts_code(code, cache_key)
        return str(js_file)

    def call_func(self, lib_path: str, func_name: str, args: tuple, ret_type: Optional[type] = None) -> Any:
        """调用编译后的 JavaScript 函数。

        Args:
            lib_path: JS 文件路径。
            func_name: 函数名称（当前未使用，入口已固化在模板中）。
            args: 函数参数元组。
            ret_type: 返回值类型（当前未使用，由 JSON 反序列化自动推断）。

        Returns:
            Any: 函数执行结果，已从 JSON 反序列化为 Python 对象。

        Raises:
            RuntimeError: Node.js 不可用或执行失败时抛出。
        """
        return _call_ts_function(Path(lib_path), list(args))

    def _get_project_hash(self, project_dir: str) -> str:
        """计算项目所有源文件的内容哈希。

        TypeScript 支持 .ts 和 .js 两种源文件扩展名。

        Args:
            project_dir: 项目根目录路径。

        Returns:
            str: 项目源文件内容的 MD5 哈希值。
        """
        import os
        import hashlib

        hasher = hashlib.md5()
        if not os.path.isdir(project_dir):
            return hasher.hexdigest()

        src_files = []
        for root, dirs, files in os.walk(project_dir):
            for f in files:
                if f.endswith('.ts') or f.endswith('.js'):
                    src_files.append(os.path.join(root, f))

        src_files.sort()

        for filepath in src_files:
            try:
                with open(filepath, 'rb') as f:
                    hasher.update(f.read())
            except Exception:
                pass

        return hasher.hexdigest()

    def compile_project(self, project_dir: str, entry: str, output_dir: Optional[str] = None) -> str:
        """编译整个 TypeScript 项目。

        扫描项目目录下所有 .ts 和 .js 文件，打包成一个可执行的 JS 文件。
        如果 entry 为 'main'，生成包含 CLI 入口的完整脚本；
        否则生成导出入口函数的模块文件。

        Args:
            project_dir: 项目目录路径。
            entry: 入口函数名，'main' 表示生成可执行脚本。
            output_dir: 输出目录，为 None 时使用缓存目录。

        Returns:
            str: 输出 JS 文件的路径。
        """
        project_path = Path(project_dir)
        files = []
        for ext in ('*.ts', '*.js'):
            files.extend(sorted(project_path.rglob(ext)))

        if not files:
            raise FileNotFoundError(f"在 {project_dir} 中未找到 .ts 或 .js 文件")

        code_hash = self._get_project_hash(project_dir)
        out_dir = Path(output_dir) if output_dir else _TS_CACHE_DIR / f'proj_{code_hash[:16]}'
        out_dir.mkdir(parents=True, exist_ok=True)

        out_file = out_dir / 'index.js'

        if out_file.exists():
            return str(out_file)

        parts = []
        parts.append('// Auto-generated by vools.bridge.typescript')
        parts.append(f'// Project: {project_dir}')
        parts.append('')

        for f in files:
            rel_path = f.relative_to(project_path)
            parts.append(f'// ---- {rel_path} ----')
            content = f.read_text(encoding='utf-8')
            if f.suffix == '.ts':
                content = _strip_typescript(content)
            parts.append(content)
            parts.append('')

        if entry == 'main':
            parts.append('// CLI entry point')
            parts.append("if (require.main === module) {")
            parts.append("    let input = '';")
            parts.append("    process.stdin.setEncoding('utf-8');")
            parts.append("    process.stdin.on('data', (chunk) => { input += chunk; });")
            parts.append("    process.stdin.on('end', async () => {")
            parts.append("        let okFlag = true;")
            parts.append("        let resultValue = null;")
            parts.append("        let errMsg = '';")
            parts.append("        try {")
            parts.append("            const data = JSON.parse(input);")
            parts.append("            const args = data.args || [];")
            parts.append("            if (typeof main === 'function') {")
            parts.append("                resultValue = await main(...args);")
            parts.append("            } else {")
            parts.append("                resultValue = null;")
            parts.append("            }")
            parts.append("        } catch (err) {")
            parts.append("            okFlag = false;")
            parts.append("            errMsg = err && err.message ? err.message : String(err);")
            parts.append("        }")
            parts.append("        const outPayload = { ok: okFlag, result: resultValue, error: errMsg };")
            parts.append("        process.stdout.write(JSON.stringify(outPayload));")
            parts.append("    });")
            parts.append("}")
        else:
            parts.append(f'// Entry: {entry}')
            parts.append(f'module.exports = {{ {entry} }};')

        out_file.write_text('\n'.join(parts), encoding='utf-8')
        return str(out_file)


# 全局实例
_ts_bridge = TypeScriptBridge()

# 装饰器：直接使用基类的 decorator 方法
ts = _ts_bridge.decorator

# typescript 是 ts 的别名
typescript = ts
