[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vools-rx"
version = "0.7.5"
authors = [
    { name = "Victor", email = "victortop921129@gmail.com" },
]
description = "vools 响应式编程子包"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = [
    "vools>=0.7.1",
]

[tool.setuptools.packages.find]
include = ["vools.reactive*"]

[tool.setuptools.package-data]
"vools.reactive" = [
    "README.md",
    "*/README.md",
    "FEATURE_COMPARISON.md",
]
