/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -IE:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_sha1.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_sha1.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ[2];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  NI len; tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content* p;
};
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NimStringV2, sha1_hash__test95sha1_u14)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__test95sha1_u46)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__test95sha1_u175)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8 y_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__9bAGqSvkAaFL9bWjsEPslrFA, newSeq__test95sha1_u244)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(NU32, rotl32__test95sha1_u2)(NU32 x_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sha1_u329)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__test95sha1_u500)(NU8 x_p0, NI len_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___test95sha1_u131)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ugDTQxRWLw6C7YgcgvsG2w_2 = { 10 | NIM_STRLIT_FLAG, "Computed: " };
static const NimStringV2 TM__ugDTQxRWLw6C7YgcgvsG2w_3 = {10, (NimStrPayload*)&TM__ugDTQxRWLw6C7YgcgvsG2w_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__ugDTQxRWLw6C7YgcgvsG2w_43 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__ugDTQxRWLw6C7YgcgvsG2w_44 = {0, (NimStrPayload*)&TM__ugDTQxRWLw6C7YgcgvsG2w_43};
static const struct {
  NI cap; NIM_CHAR data[139+1];
} TM__ugDTQxRWLw6C7YgcgvsG2w_45 = { 139 | NIM_STRLIT_FLAG, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim(254, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__ugDTQxRWLw6C7YgcgvsG2w_46 = {139, (NimStrPayload*)&TM__ugDTQxRWLw6C7YgcgvsG2w_45};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__ugDTQxRWLw6C7YgcgvsG2w_47 = { 3 | NIM_STRLIT_FLAG, "abc" };
static const NimStringV2 TM__ugDTQxRWLw6C7YgcgvsG2w_48 = {3, (NimStrPayload*)&TM__ugDTQxRWLw6C7YgcgvsG2w_47};
static const struct {
  NI cap; NIM_CHAR data[50+1];
} TM__ugDTQxRWLw6C7YgcgvsG2w_50 = { 50 | NIM_STRLIT_FLAG, "Expected: a9993e364706816aba3e25717850c26c9cd0d89d" };
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__ugDTQxRWLw6C7YgcgvsG2w_49 = {{50, (NimStrPayload*)&TM__ugDTQxRWLw6C7YgcgvsG2w_50}}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(NU32, rotl32__test95sha1_u2)(NU32 x_p0, NI n_p1) {
	NU32 result;
	NI TM__ugDTQxRWLw6C7YgcgvsG2w_16;
	nimfr_("rotl32", "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");
{	result = (NU32)0;
	nimlf_(7, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	if (nimSubInt(((NI)32), n_p1, &TM__ugDTQxRWLw6C7YgcgvsG2w_16)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NU32)((NU32)((NU64)(x_p0) << (NU64)(((NU) (n_p1)) & (32 - 1))) | (NU32)((NU32)(x_p0) >> (NU64)(((NU) ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_16))) & (32 - 1))));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, sha1_hash__test95sha1_u14)(NimStringV2 msg_p0) {
	NimStringV2 result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ data_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ digest_1;
	NI n_1;
	NU bits_1;
	NI TM__ugDTQxRWLw6C7YgcgvsG2w_5;
	NU32 H0_1;
	NU32 H1_1;
	NU32 H2_1;
	NU32 H3_1;
	NU32 H4_1;
NIM_BOOL* nimErr_;
	nimfr_("sha1_hash", "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	data_1.len = 0; data_1.p = NIM_NIL;
	digest_1.len = 0; digest_1.p = NIM_NIL;
	nimln_(10);	n_1 = msg_p0.len;
	nimln_(11);	if ((n_1) < ((NI)0) || (n_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(n_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	data_1 = newSeq__test95sha1_u46((n_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_4;
				if (!(i_2 < n_1)) goto LA3;
				nimlf_(12, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_1 = i_2;
				nimln_(13);				if (i_1 < 0 || i_1 >= data_1.len){ raiseIndexError2(i_1,data_1.len-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= msg_p0.len){ raiseIndexError2(i_1,msg_p0.len-1); goto BeforeRet_;
				}
				data_1.p->data[i_1] = ((NU8) (((NU8)(msg_p0.p->data[i_1]))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_4)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_4);
			} LA3: ;
		}
	}
	nimlf_(15, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	if (nimMulInt(n_1, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_5)) { raiseOverflow(); goto BeforeRet_;
	};
	bits_1 = ((NU) ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_5)));
	nimln_(16);	add__test95sha1_u175((&data_1), ((NU8)128));
	{
		nimln_(17);		while (1) {
			NI T6_;
			T6_ = data_1.len;
			if (!!(((NI)((T6_) % (((NI)64))) == ((NI)56)))) goto LA5;
			nimln_(18);			add__test95sha1_u175((&data_1), ((NU8)0));
		} LA5: ;
	}
	{
		NI i_3;
		NI i_4;
		i_3 = (NI)0;
		nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		i_4 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_6;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_7;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_8;
				if (!(i_4 < ((NI)8))) goto LA9;
				nimlf_(19, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_3 = i_4;
				nimln_(20);				if (nimMulInt(i_3, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_6)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)56), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_6), &TM__ugDTQxRWLw6C7YgcgvsG2w_7)) { raiseOverflow(); goto BeforeRet_;
				};
				add__test95sha1_u175((&data_1), ((NU8) ((NU)((NU)((NU64)(bits_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_7) & (64 - 1))) & ((NU)255)))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_4, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_8)) { raiseOverflow(); goto BeforeRet_;
				};
				i_4 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_8);
			} LA9: ;
		}
	}
	nimlf_(22, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	H0_1 = ((NU32)1732584193);
	nimln_(23);	H1_1 = ((NU32)IL64(4023233417));
	nimln_(24);	H2_1 = ((NU32)IL64(2562383102));
	nimln_(25);	H3_1 = ((NU32)271733878);
	nimln_(26);	H4_1 = ((NU32)IL64(3285377520));
	{
		NI i_5;
		NI colontmp_;
		NI T11_;
		NI i_6;
		i_5 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(126, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		nimlf_(28, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");		T11_ = data_1.len;
		colontmp_ = (NI)((T11_) / (((NI)64)));
		nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		i_6 = ((NI)0);
		{
			nimln_(129);			while (1) {
				tySequence__9bAGqSvkAaFL9bWjsEPslrFA W_1;
				NU32 A_1;
				NU32 B_1;
				NU32 C_1;
				NU32 D_1;
				NU32 E_1;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_23;
				if (!(i_6 < colontmp_)) goto LA13;
				W_1.len = 0; W_1.p = NIM_NIL;
				nimlf_(28, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_5 = i_6;
				nimln_(29);				W_1 = newSeq__test95sha1_u244(((NI)80));
				{
					NI j_1;
					NI i_7;
					j_1 = (NI)0;
					nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");					i_7 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NI offset_1;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_9;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_10;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_11;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_12;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_13;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_14;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_15;
							if (!(i_7 < ((NI)16))) goto LA16;
							nimlf_(30, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");							j_1 = i_7;
							nimln_(31);							if (nimMulInt(i_5, ((NI)64), &TM__ugDTQxRWLw6C7YgcgvsG2w_9)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimMulInt(j_1, ((NI)4), &TM__ugDTQxRWLw6C7YgcgvsG2w_10)) { raiseOverflow(); goto BeforeRet_;
							};
							if (nimAddInt((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_9), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_10), &TM__ugDTQxRWLw6C7YgcgvsG2w_11)) { raiseOverflow(); goto BeforeRet_;
							};
							offset_1 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_11);
							nimln_(32);							if (j_1 < 0 || j_1 >= W_1.len){ raiseIndexError2(j_1,W_1.len-1); goto BeforeRet_;
							}
							nimln_(34);							nimln_(33);							nimln_(32);							if (offset_1 < 0 || offset_1 >= data_1.len){ raiseIndexError2(offset_1,data_1.len-1); goto BeforeRet_;
							}
							nimln_(33);							if (nimAddInt(offset_1, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_12)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_12) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_12) >= data_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_12),data_1.len-1); goto BeforeRet_;
							}
							nimln_(34);							if (nimAddInt(offset_1, ((NI)2), &TM__ugDTQxRWLw6C7YgcgvsG2w_13)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_13) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_13) >= data_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_13),data_1.len-1); goto BeforeRet_;
							}
							nimln_(35);							if (nimAddInt(offset_1, ((NI)3), &TM__ugDTQxRWLw6C7YgcgvsG2w_14)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_14) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_14) >= data_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_14),data_1.len-1); goto BeforeRet_;
							}
							W_1.p->data[j_1] = (NU32)((NU32)((NU32)((NU32)((NU64)(((NU32) (data_1.p->data[offset_1]))) << (NU64)(((NI)24) & (32 - 1))) | (NU32)((NU64)(((NU32) (data_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_12)]))) << (NU64)(((NI)16) & (32 - 1)))) | (NU32)((NU64)(((NU32) (data_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_13)]))) << (NU64)(((NI)8) & (32 - 1)))) | ((NU32) (data_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_14)])));
							nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");							if (nimAddInt(i_7, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_15)) { raiseOverflow(); goto BeforeRet_;
							};
							i_7 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_15);
						} LA16: ;
					}
				}
				{
					NI j_2;
					NI i_8;
					j_2 = (NI)0;
					nimln_(128);					i_8 = ((NI)16);
					{
						nimln_(129);						while (1) {
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_17;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_18;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_19;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_20;
							NU32 T20_;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_21;
							if (!(i_8 < ((NI)80))) goto LA19;
							nimlf_(36, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");							j_2 = i_8;
							nimln_(37);							if (j_2 < 0 || j_2 >= W_1.len){ raiseIndexError2(j_2,W_1.len-1); goto BeforeRet_;
							}
							if (nimSubInt(j_2, ((NI)3), &TM__ugDTQxRWLw6C7YgcgvsG2w_17)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_17) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_17) >= W_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_17),W_1.len-1); goto BeforeRet_;
							}
							if (nimSubInt(j_2, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_18)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_18) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_18) >= W_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_18),W_1.len-1); goto BeforeRet_;
							}
							if (nimSubInt(j_2, ((NI)14), &TM__ugDTQxRWLw6C7YgcgvsG2w_19)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_19) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_19) >= W_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_19),W_1.len-1); goto BeforeRet_;
							}
							if (nimSubInt(j_2, ((NI)16), &TM__ugDTQxRWLw6C7YgcgvsG2w_20)) { raiseOverflow(); goto BeforeRet_;
							};
							if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_20) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_20) >= W_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_20),W_1.len-1); goto BeforeRet_;
							}
							T20_ = (NU32)0;
							T20_ = rotl32__test95sha1_u2((NU32)((NU32)((NU32)(W_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_17)] ^ W_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_18)]) ^ W_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_19)]) ^ W_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_20)]), ((NI)1));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							W_1.p->data[j_2] = T20_;
							nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");							if (nimAddInt(i_8, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_21)) { raiseOverflow(); goto BeforeRet_;
							};
							i_8 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_21);
						} LA19: ;
					}
				}
				nimlf_(39, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				A_1 = H0_1;
				B_1 = H1_1;
				C_1 = H2_1;
				D_1 = H3_1;
				E_1 = H4_1;
				{
					NI j_3;
					NI i_9;
					j_3 = (NI)0;
					nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");					i_9 = ((NI)0);
					{
						nimln_(129);						while (1) {
							NU32 f_1;
							NU32 k_1;
							NU32 temp_1;
							NU32 T35_;
							NI TM__ugDTQxRWLw6C7YgcgvsG2w_22;
							if (!(i_9 < ((NI)80))) goto LA23;
							nimlf_(41, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");							j_3 = i_9;
							f_1 = (NU32)0;
							k_1 = (NU32)0;
							nimln_(44);							{
								if (!(j_3 <= ((NI)19))) goto LA26_;
								nimln_(46);								f_1 = (NU32)((NU32)(B_1 & C_1) | (NU32)((NU32)((NU32) ~(B_1)) & D_1));
								nimln_(47);								k_1 = ((NU32)1518500249);
							}
							goto LA24_;
LA26_: ;
							{
								nimln_(48);								if (!(j_3 <= ((NI)39))) goto LA29_;
								nimln_(49);								f_1 = (NU32)((NU32)(B_1 ^ C_1) ^ D_1);
								nimln_(50);								k_1 = ((NU32)1859775393);
							}
							goto LA24_;
LA29_: ;
							{
								nimln_(51);								if (!(j_3 <= ((NI)59))) goto LA32_;
								nimln_(52);								f_1 = (NU32)((NU32)((NU32)(B_1 & C_1) | (NU32)(B_1 & D_1)) | (NU32)(C_1 & D_1));
								nimln_(53);								k_1 = ((NU32)IL64(2400959708));
							}
							goto LA24_;
LA32_: ;
							{
								nimln_(55);								f_1 = (NU32)((NU32)(B_1 ^ C_1) ^ D_1);
								nimln_(56);								k_1 = ((NU32)IL64(3395469782));
							}
LA24_: ;
							nimln_(58);							T35_ = (NU32)0;
							T35_ = rotl32__test95sha1_u2(A_1, ((NI)5));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (j_3 < 0 || j_3 >= W_1.len){ raiseIndexError2(j_3,W_1.len-1); goto BeforeRet_;
							}
							temp_1 = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(T35_) + (NU32)(f_1))) + (NU32)(E_1))) + (NU32)(W_1.p->data[j_3]))) + (NU32)(k_1));
							nimln_(59);							E_1 = D_1;
							nimln_(60);							D_1 = C_1;
							nimln_(61);							C_1 = rotl32__test95sha1_u2(B_1, ((NI)30));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							nimln_(62);							B_1 = A_1;
							nimln_(63);							A_1 = temp_1;
							nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");							if (nimAddInt(i_9, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_22)) { raiseOverflow(); goto BeforeRet_;
							};
							i_9 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_22);
						} LA23: ;
					}
				}
				nimlf_(65, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				H0_1 = (NU32)((NU32)(H0_1) + (NU32)(A_1));
				H1_1 = (NU32)((NU32)(H1_1) + (NU32)(B_1));
				H2_1 = (NU32)((NU32)(H2_1) + (NU32)(C_1));
				H3_1 = (NU32)((NU32)(H3_1) + (NU32)(D_1));
				H4_1 = (NU32)((NU32)(H4_1) + (NU32)(E_1));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_6, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_23)) { raiseOverflow(); goto BeforeRet_;
				};
				i_6 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_23);
				nimlf_(651, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				eqdestroy___test95sha1_u329(W_1);
			} LA13: ;
		}
	}
	nimlf_(67, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	digest_1 = newSeq__test95sha1_u46(((NI)20));
	{
		NI i_10;
		NI i_11;
		i_10 = (NI)0;
		nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		i_11 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_24;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_25;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_26;
				if (!(i_11 < ((NI)4))) goto LA38;
				nimlf_(68, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_10 = i_11;
				nimln_(69);				if (i_10 < 0 || i_10 >= digest_1.len){ raiseIndexError2(i_10,digest_1.len-1); goto BeforeRet_;
				}
				if (nimMulInt(i_10, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_24)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)24), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_24), &TM__ugDTQxRWLw6C7YgcgvsG2w_25)) { raiseOverflow(); goto BeforeRet_;
				};
				digest_1.p->data[i_10] = ((NU8) ((NU32)((NU32)((NU32)(H0_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_25) & (32 - 1))) & ((NU32)255))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_11, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_26)) { raiseOverflow(); goto BeforeRet_;
				};
				i_11 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_26);
			} LA38: ;
		}
	}
	{
		NI i_12;
		NI i_13;
		i_12 = (NI)0;
		nimln_(128);		i_13 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_27;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_28;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_29;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_30;
				if (!(i_13 < ((NI)4))) goto LA41;
				nimlf_(70, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_12 = i_13;
				nimln_(71);				if (nimAddInt(((NI)4), i_12, &TM__ugDTQxRWLw6C7YgcgvsG2w_27)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_27) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_27) >= digest_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_27),digest_1.len-1); goto BeforeRet_;
				}
				if (nimMulInt(i_12, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_28)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)24), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_28), &TM__ugDTQxRWLw6C7YgcgvsG2w_29)) { raiseOverflow(); goto BeforeRet_;
				};
				digest_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_27)] = ((NU8) ((NU32)((NU32)((NU32)(H1_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_29) & (32 - 1))) & ((NU32)255))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_13, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_30)) { raiseOverflow(); goto BeforeRet_;
				};
				i_13 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_30);
			} LA41: ;
		}
	}
	{
		NI i_14;
		NI i_15;
		i_14 = (NI)0;
		nimln_(128);		i_15 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_31;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_32;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_33;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_34;
				if (!(i_15 < ((NI)4))) goto LA44;
				nimlf_(72, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_14 = i_15;
				nimln_(73);				if (nimAddInt(((NI)8), i_14, &TM__ugDTQxRWLw6C7YgcgvsG2w_31)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_31) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_31) >= digest_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_31),digest_1.len-1); goto BeforeRet_;
				}
				if (nimMulInt(i_14, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_32)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)24), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_32), &TM__ugDTQxRWLw6C7YgcgvsG2w_33)) { raiseOverflow(); goto BeforeRet_;
				};
				digest_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_31)] = ((NU8) ((NU32)((NU32)((NU32)(H2_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_33) & (32 - 1))) & ((NU32)255))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_15, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_34)) { raiseOverflow(); goto BeforeRet_;
				};
				i_15 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_34);
			} LA44: ;
		}
	}
	{
		NI i_16;
		NI i_17;
		i_16 = (NI)0;
		nimln_(128);		i_17 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_35;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_36;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_37;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_38;
				if (!(i_17 < ((NI)4))) goto LA47;
				nimlf_(74, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_16 = i_17;
				nimln_(75);				if (nimAddInt(((NI)12), i_16, &TM__ugDTQxRWLw6C7YgcgvsG2w_35)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_35) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_35) >= digest_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_35),digest_1.len-1); goto BeforeRet_;
				}
				if (nimMulInt(i_16, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_36)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)24), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_36), &TM__ugDTQxRWLw6C7YgcgvsG2w_37)) { raiseOverflow(); goto BeforeRet_;
				};
				digest_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_35)] = ((NU8) ((NU32)((NU32)((NU32)(H3_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_37) & (32 - 1))) & ((NU32)255))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_17, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_38)) { raiseOverflow(); goto BeforeRet_;
				};
				i_17 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_38);
			} LA47: ;
		}
	}
	{
		NI i_18;
		NI i_19;
		i_18 = (NI)0;
		nimln_(128);		i_19 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_39;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_40;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_41;
				NI TM__ugDTQxRWLw6C7YgcgvsG2w_42;
				if (!(i_19 < ((NI)4))) goto LA50;
				nimlf_(76, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				i_18 = i_19;
				nimln_(77);				if (nimAddInt(((NI)16), i_18, &TM__ugDTQxRWLw6C7YgcgvsG2w_39)) { raiseOverflow(); goto BeforeRet_;
				};
				if ((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_39) < 0 || (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_39) >= digest_1.len){ raiseIndexError2((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_39),digest_1.len-1); goto BeforeRet_;
				}
				if (nimMulInt(i_18, ((NI)8), &TM__ugDTQxRWLw6C7YgcgvsG2w_40)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimSubInt(((NI)24), (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_40), &TM__ugDTQxRWLw6C7YgcgvsG2w_41)) { raiseOverflow(); goto BeforeRet_;
				};
				digest_1.p->data[(NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_39)] = ((NU8) ((NU32)((NU32)((NU32)(H4_1) >> (NU64)((NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_41) & (32 - 1))) & ((NU32)255))));
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_19, ((NI)1), &TM__ugDTQxRWLw6C7YgcgvsG2w_42)) { raiseOverflow(); goto BeforeRet_;
				};
				i_19 = (NI)(TM__ugDTQxRWLw6C7YgcgvsG2w_42);
			} LA50: ;
		}
	}
	nimlf_(80, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	result = TM__ugDTQxRWLw6C7YgcgvsG2w_44;
	{
		NU8* b_1;
		NI i_20;
		NI L_1;
		NI T52_;
		b_1 = (NU8*)0;
		nimlf_(249, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");		i_20 = ((NI)0);
		nimln_(250);		T52_ = digest_1.len;
		L_1 = T52_;
		{
			nimln_(251);			while (1) {
				NimStringV2 colontmpD_;
				if (!(i_20 < L_1)) goto LA54;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimlf_(81, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");				if (i_20 < 0 || i_20 >= digest_1.len){ raiseIndexError2(i_20,digest_1.len-1); goto BeforeRet_;
				}
				b_1 = (&digest_1.p->data[i_20]);
				nimln_(82);				colontmpD_ = toHex__test95sha1_u500((*b_1), ((NI)2));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
				nimlf_(13, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");				i_20 += ((NI)1);
				nimln_(254);				{
					NI T57_;
					T57_ = digest_1.len;
					if (!!((T57_ == L_1))) goto LA58_;
					failedAssertImpl__stdZassertions_u95(TM__ugDTQxRWLw6C7YgcgvsG2w_46);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA58_: ;
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			} LA54: ;
		}
	}
	nimln_(651);	eqdestroy___test95sha1_u131(digest_1);
	eqdestroy___test95sha1_u131(data_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatsexitprocsdotnim_Init000();
	atpstdatssynciodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("test_sha1", "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(84, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1.nim");	T2_[0] = TM__ugDTQxRWLw6C7YgcgvsG2w_3;
	colontmpD_ = sha1_hash__test95sha1_u14(TM__ugDTQxRWLw6C7YgcgvsG2w_48);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1] = colontmpD_;
	echoBinSafe(T2_, 2);
	nimln_(85);	echoBinSafe(TM__ugDTQxRWLw6C7YgcgvsG2w_49, 1);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

