/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_minimal.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_minimal.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

N_LIB_PRIVATE N_NIMCALL(int, test_add)(int a_p0, int b_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, test_str)(NCSTRING s_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(int, test_add)(int a_p0, int b_p1) {
	int result;
	NI TM__vvmu84nLbVoebXh1wvNoMA_2;
	nimfr_("test_add", "e:\\IDEProjects\\AI\\vools\\nim_core\\test_minimal.nim");
{	result = (int)0;
	nimlf_(5, "e:\\IDEProjects\\AI\\vools\\nim_core\\test_minimal.nim");	if (nimAddInt(a_p0, b_p1, &TM__vvmu84nLbVoebXh1wvNoMA_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (TM__vvmu84nLbVoebXh1wvNoMA_2 < (-2147483647 -1) || TM__vvmu84nLbVoebXh1wvNoMA_2 > 2147483647){ raiseOverflow(); goto BeforeRet_;
	}
	result = (NI32)(TM__vvmu84nLbVoebXh1wvNoMA_2);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, test_str)(NCSTRING s_p0, int len_p1) {
	NCSTRING result;
	nimfr_("test_str", "e:\\IDEProjects\\AI\\vools\\nim_core\\test_minimal.nim");
	nimln_(8);	result = "hello";
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(void, NimDestroyGlobals)(void) {
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatssynciodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fwdreason, 
                    LPVOID lpvReserved) {
	if (fwdreason == DLL_PROCESS_ATTACH) {
	NimMain();
	}
	return 1;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

