/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -IE:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_sha1_func.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@mtest_sha1_func.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ[2];
typedef NimStringV2 tyArray__YgExxhfgKcesA5EOUj1MOA[1];
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__test95sha195func_u6)(NU32 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args_p0, NI args_p0Len_0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatsexitprocsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__amX261jHOQ7yScyHsszWxQ_2 = { 10 | NIM_STRLIT_FLAG, "not B = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_3 = {10, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_2};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__amX261jHOQ7yScyHsszWxQ_4 = { 12 | NIM_STRLIT_FLAG, "B and C = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_5 = {12, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_4};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__amX261jHOQ7yScyHsszWxQ_6 = { 18 | NIM_STRLIT_FLAG, "(not B) and D = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_7 = {18, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_6};
static const struct {
  NI cap; NIM_CHAR data[37+1];
} TM__amX261jHOQ7yScyHsszWxQ_8 = { 37 | NIM_STRLIT_FLAG, "F = (B and C) or ((not B) and D) = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_9 = {37, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_8};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__amX261jHOQ7yScyHsszWxQ_11 = { 20 | NIM_STRLIT_FLAG, "Expected: 0x10325476" };
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__amX261jHOQ7yScyHsszWxQ_12 = { 18 | NIM_STRLIT_FLAG, "B xor C xor D = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_13 = {18, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_12};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__amX261jHOQ7yScyHsszWxQ_14 = { 19 | NIM_STRLIT_FLAG, "F2 with parens = 0x" };
static const NimStringV2 TM__amX261jHOQ7yScyHsszWxQ_15 = {19, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_14};
static NIM_CONST tyArray__YgExxhfgKcesA5EOUj1MOA TM__amX261jHOQ7yScyHsszWxQ_10 = {{20, (NimStrPayload*)&TM__amX261jHOQ7yScyHsszWxQ_11}}
;
N_LIB_PRIVATE NIM_CONST NU32 B__test95sha195func_u2 = ((NU32)IL64(4023233417));
N_LIB_PRIVATE NIM_CONST NU32 C__test95sha195func_u3 = ((NU32)IL64(2562383102));
N_LIB_PRIVATE NIM_CONST NU32 D__test95sha195func_u4 = ((NU32)271733878);
N_LIB_PRIVATE NU32 notB__test95sha195func_u5;
N_LIB_PRIVATE NU32 bandc__test95sha195func_u14;
N_LIB_PRIVATE NU32 notbandd__test95sha195func_u18;
N_LIB_PRIVATE NU32 f__test95sha195func_u22;
N_LIB_PRIVATE NU32 fxor__test95sha195func_u26;
N_LIB_PRIVATE NU32 f2__test95sha195func_u30;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatsexitprocsdotnim_Init000();
	atpstdatssynciodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpstdatssynciodotnim_DatInit000();
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	NimStringV2 colontmpD__5;
	NimStringV2 colontmpD__6;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T2_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T3_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T4_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T5_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T6_;
	tyArray__pK4u9cQ1bJzH46rrmNu9bPMQ T7_;
NIM_BOOL* nimErr_;
	nimfr_("test_sha1_func", "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1_func.nim");
nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
	nimlf_(9, "E:\\IDEProjects\\AI\\vools\\nim_core\\test_sha1_func.nim");	notB__test95sha195func_u5 = (NU32)((NU32) ~(B__test95sha195func_u2));
	nimln_(10);	T2_[0] = TM__amX261jHOQ7yScyHsszWxQ_3;
	colontmpD_ = toHex__test95sha195func_u6(notB__test95sha195func_u5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1] = colontmpD_;
	echoBinSafe(T2_, 2);
	nimln_(11);	bandc__test95sha195func_u14 = (NU32)(B__test95sha195func_u2 & C__test95sha195func_u3);
	nimln_(12);	T3_[0] = TM__amX261jHOQ7yScyHsszWxQ_5;
	colontmpD__2 = toHex__test95sha195func_u6(bandc__test95sha195func_u14);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_[1] = colontmpD__2;
	echoBinSafe(T3_, 2);
	nimln_(13);	notbandd__test95sha195func_u18 = (NU32)((NU32)((NU32) ~(B__test95sha195func_u2)) & D__test95sha195func_u4);
	nimln_(14);	T4_[0] = TM__amX261jHOQ7yScyHsszWxQ_7;
	colontmpD__3 = toHex__test95sha195func_u6(notbandd__test95sha195func_u18);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T4_[1] = colontmpD__3;
	echoBinSafe(T4_, 2);
	nimln_(15);	f__test95sha195func_u22 = (NU32)(bandc__test95sha195func_u14 | notbandd__test95sha195func_u18);
	nimln_(16);	T5_[0] = TM__amX261jHOQ7yScyHsszWxQ_9;
	colontmpD__4 = toHex__test95sha195func_u6(f__test95sha195func_u22);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_[1] = colontmpD__4;
	echoBinSafe(T5_, 2);
	nimln_(17);	echoBinSafe(TM__amX261jHOQ7yScyHsszWxQ_10, 1);
	nimln_(20);	fxor__test95sha195func_u26 = (NU32)((NU32)(B__test95sha195func_u2 ^ C__test95sha195func_u3) ^ D__test95sha195func_u4);
	nimln_(21);	T6_[0] = TM__amX261jHOQ7yScyHsszWxQ_13;
	colontmpD__5 = toHex__test95sha195func_u6(fxor__test95sha195func_u26);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T6_[1] = colontmpD__5;
	echoBinSafe(T6_, 2);
	nimln_(24);	f2__test95sha195func_u30 = (NU32)((NU32)(B__test95sha195func_u2 & C__test95sha195func_u3) | (NU32)((NU32)((NU32) ~(B__test95sha195func_u2)) & D__test95sha195func_u4));
	nimln_(25);	T7_[0] = TM__amX261jHOQ7yScyHsszWxQ_15;
	colontmpD__6 = toHex__test95sha195func_u6(f2__test95sha195func_u30);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_[1] = colontmpD__6;
	echoBinSafe(T7_, 2);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

