/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@mvools_encoding.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@mvools_encoding.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <windows.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(NCSTRING, base64_encode)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, cstrToBytes__vools95encoding_u2)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, newSeq__vools95encoding_u35)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95encoding_u120)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, encode__vools95encoding_u329)(NU8* s_p0, NI s_p0Len_0, NIM_BOOL safe_p1);
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8674)(NimStringV2* s_p0, NI i_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, base64_decode)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToString__vools95encoding_u159)(NCSTRING data_p0, int len_p1);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, decode__pureZbase64_u500)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(int, base64_decode_len)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, zlib_compress)(NCSTRING data_p0, int len_p1, int level_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, rleCompress__vools95encoding_u164)(NU8* data_p0, NI data_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__vools95encoding_u190)(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* x_p0, NU8 y_p1);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, zlib_decompress)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, rleDecompress__vools95encoding_u259)(NU8* data_p0, NI data_p0Len_0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(int, zlib_decompress_len)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, gzip_compress)(NCSTRING data_p0, int len_p1, int level_p2);
N_LIB_PRIVATE N_NIMCALL(NCSTRING, gzip_decompress)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(int, gzip_decompress_len)(NCSTRING data_p0, int len_p1);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atpsystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__KQgpv7UNmU0GotFZvsDdZQ_5 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__KQgpv7UNmU0GotFZvsDdZQ_6 = {0, (NimStrPayload*)&TM__KQgpv7UNmU0GotFZvsDdZQ_5};
static const struct {
  NI cap; NIM_CHAR data[139+1];
} TM__KQgpv7UNmU0GotFZvsDdZQ_22 = { 139 | NIM_STRLIT_FLAG, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim(187, 11) `len(a) == L` the length of the seq changed while iterating over it" };
static const NimStringV2 TM__KQgpv7UNmU0GotFZvsDdZQ_23 = {139, (NimStrPayload*)&TM__KQgpv7UNmU0GotFZvsDdZQ_22};
static const NimStringV2 TM__KQgpv7UNmU0GotFZvsDdZQ_25 = {139, (NimStrPayload*)&TM__KQgpv7UNmU0GotFZvsDdZQ_22};
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, cstrToBytes__vools95encoding_u2)(NCSTRING data_p0, int len_p1) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI n_1;
	nimfr_("cstrToBytes", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(10, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	n_1 = ((NI) (len_p1));
	nimln_(11);	if ((n_1) < ((NI)0) || (n_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(n_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = newSeq__vools95encoding_u35((n_1));
	{
		NI i_1;
		NI i_2;
		i_1 = (NI)0;
		nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		i_2 = ((NI)0);
		{
			nimln_(129);			while (1) {
				NI TM__KQgpv7UNmU0GotFZvsDdZQ_2;
				if (!(i_2 < n_1)) goto LA3;
				nimlf_(12, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");				i_1 = i_2;
				nimln_(13);				if (i_1 < 0 || i_1 >= result.len){ raiseIndexError2(i_1,result.len-1); goto BeforeRet_;
				}
				result.p->data[i_1] = ((NU8*) (data_p0))[i_1];
				nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_2 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_2);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_u8674)(NimStringV2* s_p0, NI i_p1) {
	NIM_CHAR* result;
	NI TM__KQgpv7UNmU0GotFZvsDdZQ_3;
	nimfr_("[]", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\indices.nim");
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s_p0)));
	if (nimSubInt((*s_p0).len, i_p1, &TM__KQgpv7UNmU0GotFZvsDdZQ_3)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_3) < 0 || (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_3) >= (*s_p0).len){ raiseIndexError2((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_3),(*s_p0).len-1); goto BeforeRet_;
	}
	result = (&(*s_p0).p->data[(NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_3)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, base64_encode)(NCSTRING data_p0, int len_p1) {
	NCSTRING result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	NimStringV2 enc_1;
NIM_BOOL* nimErr_;
	nimfr_("base64_encode", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	enc_1.len = 0; enc_1.p = NIM_NIL;
	nimlf_(74, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	bytes_1 = cstrToBytes__vools95encoding_u2(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(75);	{
		NI T4_;
		T4_ = bytes_1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(76);		result = "";
		nimln_(77);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(bytes_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(78, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	enc_1 = encode__vools95encoding_u329(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(80);		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			NI TM__KQgpv7UNmU0GotFZvsDdZQ_4;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI)0) < enc_1.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_u8674((&enc_1), ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			T9_ = ((NU8)((*T11_)) == (NU8)(61));
LA10_: ;
			if (!T9_) goto LA8;
			nimln_(81);			if (nimSubInt(enc_1.len, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_4)) { raiseOverflow(); goto LA1_;
			};
			if (((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_4)) < ((NI)0) || ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_4), ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
			}
			setLengthStrV2((&enc_1), ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_4)));
		} LA8: ;
	}
	nimln_(82);	result = nimToCStringConv(enc_1);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(bytes_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToString__vools95encoding_u159)(NCSTRING data_p0, int len_p1) {
	NimStringV2 result;
	NI n_1;
	nimfr_("cstrToString", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(16, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	n_1 = ((NI) (len_p1));
	nimln_(17);	{
		if (!(n_1 <= ((NI)0))) goto LA3_;
		nimln_(18);		result = TM__KQgpv7UNmU0GotFZvsDdZQ_6;
		nimln_(19);		goto BeforeRet_;
	}
LA3_: ;
	nimln_(20);	if ((n_1) < ((NI)0) || (n_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(n_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	result = mnewString((n_1));
	nimln_(21);	if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
	}
	if ((n_1) < ((NI)0) || (n_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(n_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	copyMem__system_u1755(((void*) ((&result.p->data[((NI)0)]))), ((void*) ((&data_p0[((NI)0)]))), (n_1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, base64_decode)(NCSTRING data_p0, int len_p1) {
	NCSTRING result;
	NimStringV2 s_1;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("base64_decode", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(85);	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(86);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(87);		result = "";
		nimln_(88);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(89, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	colontmpD_ = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = nimToCStringConv(colontmpD_);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, base64_decode_len)(NCSTRING data_p0, int len_p1) {
	int result;
	NimStringV2 s_1;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("base64_decode_len", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(92, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(93);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(94);		result = ((int)0);
		nimln_(95);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(96, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	colontmpD_ = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if ((colontmpD_.len) < ((int)(-2147483647 -1)) || (colontmpD_.len) > ((int)2147483647)){ raiseRangeErrorI(colontmpD_.len, ((int)(-2147483647 -1)), ((int)2147483647)); goto LA1_;
	}
	result = ((int) (colontmpD_.len));
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, rleCompress__vools95encoding_u164)(NU8* data_p0, NI data_p0Len_0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI i_1;
	nimfr_("rleCompress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{	nimlf_(28, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	nimln_(29);	i_1 = ((NI)0);
	{
		nimln_(30);		while (1) {
			NI start_1;
			NI count_1;
			NI TM__KQgpv7UNmU0GotFZvsDdZQ_12;
			if (!(i_1 < data_p0Len_0)) goto LA2;
			nimln_(31);			start_1 = i_1;
			nimln_(32);			count_1 = ((NI)1);
			{
				nimln_(33);				while (1) {
					NIM_BOOL T5_;
					NIM_BOOL T6_;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_7;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_8;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_9;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_10;
					T5_ = (NIM_BOOL)0;
					T6_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_7)) { raiseOverflow(); goto BeforeRet_;
					};
					T6_ = ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_7) < data_p0Len_0);
					if (!(T6_)) goto LA7_;
					if (i_1 < 0 || i_1 >= data_p0Len_0){ raiseIndexError2(i_1,data_p0Len_0-1); goto BeforeRet_;
					}
					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_8)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_8) < 0 || (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_8) >= data_p0Len_0){ raiseIndexError2((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_8),data_p0Len_0-1); goto BeforeRet_;
					}
					T6_ = (data_p0[i_1] == data_p0[(NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_8)]);
LA7_: ;
					T5_ = T6_;
					if (!(T5_)) goto LA8_;
					T5_ = (count_1 < ((NI)255));
LA8_: ;
					if (!T5_) goto LA4;
					nimln_(34);					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_9)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_9);
					nimln_(35);					if (nimAddInt(count_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_10)) { raiseOverflow(); goto BeforeRet_;
					};
					count_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_10);
				} LA4: ;
			}
			nimln_(36);			{
				if (!(((NI)3) <= count_1)) goto LA11_;
				nimln_(37);				add__vools95encoding_u190((&result), ((NU8)255));
				nimln_(38);				add__vools95encoding_u190((&result), ((NU8) (count_1)));
				nimln_(39);				if (start_1 < 0 || start_1 >= data_p0Len_0){ raiseIndexError2(start_1,data_p0Len_0-1); goto BeforeRet_;
				}
				add__vools95encoding_u190((&result), data_p0[start_1]);
			}
			goto LA9_;
LA11_: ;
			{
				nimln_(41);				add__vools95encoding_u190((&result), ((NU8)0));
				nimln_(42);				add__vools95encoding_u190((&result), ((NU8) (count_1)));
				{
					NI j_1;
					NI res_1;
					j_1 = (NI)0;
					nimlf_(96, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");					res_1 = start_1;
					{
						nimln_(97);						while (1) {
							NI TM__KQgpv7UNmU0GotFZvsDdZQ_11;
							if (!(res_1 <= i_1)) goto LA16;
							nimlf_(43, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");							j_1 = ((NI) (res_1));
							nimln_(44);							if (j_1 < 0 || j_1 >= data_p0Len_0){ raiseIndexError2(j_1,data_p0Len_0-1); goto BeforeRet_;
							}
							add__vools95encoding_u190((&result), data_p0[j_1]);
							nimlf_(102, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");							if (nimAddInt(res_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_11)) { raiseOverflow(); goto BeforeRet_;
							};
							res_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_11);
						} LA16: ;
					}
				}
			}
LA9_: ;
			nimlf_(45, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");			if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_12)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_12);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, zlib_compress)(NCSTRING data_p0, int len_p1, int level_p2) {
	NCSTRING result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ compressed_1;
	NimStringV2 enc_1;
NIM_BOOL* nimErr_;
	nimfr_("zlib_compress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	compressed_1.len = 0; compressed_1.p = NIM_NIL;
	enc_1.len = 0; enc_1.p = NIM_NIL;
	nimln_(103);	bytes_1 = cstrToBytes__vools95encoding_u2(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(104);	{
		NI T4_;
		T4_ = bytes_1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(105);		result = "";
		nimln_(106);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(compressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(107, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	compressed_1 = rleCompress__vools95encoding_u164(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(108);	enc_1 = encode__vools95encoding_u329(((compressed_1).p) ? (compressed_1.p->data) : NIM_NIL, compressed_1.len, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(109);		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			NI TM__KQgpv7UNmU0GotFZvsDdZQ_13;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI)0) < enc_1.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_u8674((&enc_1), ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			T9_ = ((NU8)((*T11_)) == (NU8)(61));
LA10_: ;
			if (!T9_) goto LA8;
			nimln_(110);			if (nimSubInt(enc_1.len, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_13)) { raiseOverflow(); goto LA1_;
			};
			if (((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_13)) < ((NI)0) || ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_13)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_13), ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
			}
			setLengthStrV2((&enc_1), ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_13)));
		} LA8: ;
	}
	nimln_(111);	result = nimToCStringConv(enc_1);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(compressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ, rleDecompress__vools95encoding_u259)(NU8* data_p0, NI data_p0Len_0) {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ result;
	NI i_1;
	nimfr_("rleDecompress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{	nimlf_(48, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	result.len = 0; result.p = (tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content*) newSeqPayload(0, sizeof(NU8), NIM_ALIGNOF(NU8));
	nimln_(49);	i_1 = ((NI)0);
	{
		nimln_(50);		while (1) {
			NU8 marker_1;
			NI TM__KQgpv7UNmU0GotFZvsDdZQ_14;
			if (!(i_1 < data_p0Len_0)) goto LA2;
			nimln_(51);			if (i_1 < 0 || i_1 >= data_p0Len_0){ raiseIndexError2(i_1,data_p0Len_0-1); goto BeforeRet_;
			}
			marker_1 = data_p0[i_1];
			nimln_(52);			if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_14)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_14);
			nimln_(53);			{
				if (!(marker_1 == ((NU8)255))) goto LA5_;
				nimln_(54);				{
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_15;
					NI count_1;
					NU8 value_1;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_16;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_17;
					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_15)) { raiseOverflow(); goto BeforeRet_;
					};
					if (!((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_15) < data_p0Len_0)) goto LA9_;
					nimln_(55);					if (i_1 < 0 || i_1 >= data_p0Len_0){ raiseIndexError2(i_1,data_p0Len_0-1); goto BeforeRet_;
					}
					count_1 = ((NI) (data_p0[i_1]));
					nimln_(56);					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_16)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_16) < 0 || (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_16) >= data_p0Len_0){ raiseIndexError2((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_16),data_p0Len_0-1); goto BeforeRet_;
					}
					value_1 = data_p0[(NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_16)];
					nimln_(57);					if (nimAddInt(i_1, ((NI)2), &TM__KQgpv7UNmU0GotFZvsDdZQ_17)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_17);
					{
						NI j_1;
						NI i_2;
						j_1 = (NI)0;
						nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");						i_2 = ((NI)0);
						{
							nimln_(129);							while (1) {
								NI TM__KQgpv7UNmU0GotFZvsDdZQ_18;
								if (!(i_2 < count_1)) goto LA13;
								nimlf_(58, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");								j_1 = i_2;
								nimln_(59);								add__vools95encoding_u190((&result), value_1);
								nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");								if (nimAddInt(i_2, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_18)) { raiseOverflow(); goto BeforeRet_;
								};
								i_2 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_18);
							} LA13: ;
						}
					}
				}
LA9_: ;
			}
			goto LA3_;
LA5_: ;
			{
				nimlf_(60, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");				if (!(marker_1 == ((NU8)0))) goto LA15_;
				nimln_(61);				{
					NI count_2;
					NI TM__KQgpv7UNmU0GotFZvsDdZQ_19;
					if (!(i_1 < data_p0Len_0)) goto LA19_;
					nimln_(62);					if (i_1 < 0 || i_1 >= data_p0Len_0){ raiseIndexError2(i_1,data_p0Len_0-1); goto BeforeRet_;
					}
					count_2 = ((NI) (data_p0[i_1]));
					nimln_(63);					if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_19)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_19);
					{
						NI j_2;
						NI i_3;
						j_2 = (NI)0;
						nimlf_(128, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");						i_3 = ((NI)0);
						{
							nimln_(129);							while (1) {
								NI TM__KQgpv7UNmU0GotFZvsDdZQ_21;
								if (!(i_3 < count_2)) goto LA23;
								nimlf_(64, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");								j_2 = i_3;
								nimln_(65);								{
									NI TM__KQgpv7UNmU0GotFZvsDdZQ_20;
									if (!(i_1 < data_p0Len_0)) goto LA26_;
									nimln_(66);									if (i_1 < 0 || i_1 >= data_p0Len_0){ raiseIndexError2(i_1,data_p0Len_0-1); goto BeforeRet_;
									}
									add__vools95encoding_u190((&result), data_p0[i_1]);
									nimln_(67);									if (nimAddInt(i_1, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_20)) { raiseOverflow(); goto BeforeRet_;
									};
									i_1 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_20);
								}
LA26_: ;
								nimlf_(131, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");								if (nimAddInt(i_3, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_21)) { raiseOverflow(); goto BeforeRet_;
								};
								i_3 = (NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_21);
							} LA23: ;
						}
					}
				}
LA19_: ;
			}
			goto LA3_;
LA15_: ;
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, zlib_decompress)(NCSTRING data_p0, int len_p1) {
	NCSTRING result;
	NimStringV2 s_1;
	NimStringV2 decoded_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ decompressed_1;
	NimStringV2 colontmpD_;
	NimStringV2 blitTmp_1;
	NI T6_;
NIM_BOOL* nimErr_;
	nimfr_("zlib_decompress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	decoded_1.len = 0; decoded_1.p = NIM_NIL;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	decompressed_1.len = 0; decompressed_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(114, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(115);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(116);		result = "";
		nimln_(117);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(118, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decoded_1 = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(119);	blitTmp_1 = decoded_1;
	nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	eqwasMoved___system_u2720((&decoded_1));
	bytes_1 = (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&blitTmp_1));
	nimlf_(120, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decompressed_1 = rleDecompress__vools95encoding_u259(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(121);	T6_ = decompressed_1.len;
	if ((T6_) < ((NI)0) || (T6_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T6_, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	colontmpD_ = mnewString((T6_));
	result = nimToCStringConv(colontmpD_);
	{
		NI i_1;
		NU8 b_1;
		NI i_2;
		NI L_1;
		NI T8_;
		i_1 = (NI)0;
		b_1 = (NU8)0;
		nimlf_(182, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");		i_2 = ((NI)0);
		nimln_(183);		T8_ = decompressed_1.len;
		L_1 = T8_;
		{
			nimln_(184);			while (1) {
				if (!(i_2 < L_1)) goto LA10;
				nimlf_(122, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");				i_1 = i_2;
				if (i_2 < 0 || i_2 >= decompressed_1.len){ raiseIndexError2(i_2,decompressed_1.len-1); goto LA1_;
				}
				b_1 = decompressed_1.p->data[i_2];
				nimln_(123);				if ((((NI) (b_1))) < ((NI)0) || (((NI) (b_1))) > ((NI)255)){ raiseRangeErrorI(((NI) (b_1)), ((NI)0), ((NI)255)); goto LA1_;
				}
				result[i_1] = ((NIM_CHAR) ((((NI) (b_1)))));
				nimlf_(13, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");				i_2 += ((NI)1);
				nimln_(187);				{
					NI T13_;
					T13_ = decompressed_1.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__KQgpv7UNmU0GotFZvsDdZQ_23);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA14_: ;
			} LA10: ;
		}
	}
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, zlib_decompress_len)(NCSTRING data_p0, int len_p1) {
	int result;
	NimStringV2 s_1;
	NimStringV2 decoded_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ decompressed_1;
	NimStringV2 blitTmp_1;
	NI T6_;
NIM_BOOL* nimErr_;
	nimfr_("zlib_decompress_len", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	decoded_1.len = 0; decoded_1.p = NIM_NIL;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	decompressed_1.len = 0; decompressed_1.p = NIM_NIL;
	nimlf_(126, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(127);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(128);		result = ((int)0);
		nimln_(129);		nimlf_(651, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(130, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decoded_1 = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(131);	blitTmp_1 = decoded_1;
	nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	eqwasMoved___system_u2720((&decoded_1));
	bytes_1 = (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&blitTmp_1));
	nimlf_(132, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decompressed_1 = rleDecompress__vools95encoding_u259(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(133);	T6_ = decompressed_1.len;
	if ((T6_) < ((int)(-2147483647 -1)) || (T6_) > ((int)2147483647)){ raiseRangeErrorI(T6_, ((int)(-2147483647 -1)), ((int)2147483647)); goto LA1_;
	}
	result = ((int) (T6_));
	{
		LA1_:;
	}
	{
		nimlf_(651, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, gzip_compress)(NCSTRING data_p0, int len_p1, int level_p2) {
	NCSTRING result;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ compressed_1;
	NimStringV2 enc_1;
NIM_BOOL* nimErr_;
	nimfr_("gzip_compress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	compressed_1.len = 0; compressed_1.p = NIM_NIL;
	enc_1.len = 0; enc_1.p = NIM_NIL;
	nimlf_(140, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	bytes_1 = cstrToBytes__vools95encoding_u2(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(141);	{
		NI T4_;
		T4_ = bytes_1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		nimln_(142);		result = "";
		nimln_(143);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(compressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		goto BeforeRet_;
	}
LA5_: ;
	nimlf_(144, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	compressed_1 = rleCompress__vools95encoding_u164(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(145);	enc_1 = encode__vools95encoding_u329(((compressed_1).p) ? (compressed_1.p->data) : NIM_NIL, compressed_1.len, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(146);		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			NI TM__KQgpv7UNmU0GotFZvsDdZQ_24;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI)0) < enc_1.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_u8674((&enc_1), ((NI)1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			T9_ = ((NU8)((*T11_)) == (NU8)(61));
LA10_: ;
			if (!T9_) goto LA8;
			nimln_(147);			if (nimSubInt(enc_1.len, ((NI)1), &TM__KQgpv7UNmU0GotFZvsDdZQ_24)) { raiseOverflow(); goto LA1_;
			};
			if (((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_24)) < ((NI)0) || ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_24)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_24), ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
			}
			setLengthStrV2((&enc_1), ((NI)(TM__KQgpv7UNmU0GotFZvsDdZQ_24)));
		} LA8: ;
	}
	nimln_(148);	result = nimToCStringConv(enc_1);
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (enc_1.p && !(enc_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(enc_1.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(compressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING, gzip_decompress)(NCSTRING data_p0, int len_p1) {
	NCSTRING result;
	NimStringV2 s_1;
	NimStringV2 decoded_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ decompressed_1;
	NimStringV2 colontmpD_;
	NimStringV2 blitTmp_1;
	NI T6_;
NIM_BOOL* nimErr_;
	nimfr_("gzip_decompress", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	decoded_1.len = 0; decoded_1.p = NIM_NIL;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	decompressed_1.len = 0; decompressed_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(151, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(152);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(153);		result = "";
		nimln_(154);		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(155, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decoded_1 = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(156);	blitTmp_1 = decoded_1;
	nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	eqwasMoved___system_u2720((&decoded_1));
	bytes_1 = (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&blitTmp_1));
	nimlf_(157, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decompressed_1 = rleDecompress__vools95encoding_u259(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(158);	T6_ = decompressed_1.len;
	if ((T6_) < ((NI)0) || (T6_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T6_, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
	}
	colontmpD_ = mnewString((T6_));
	result = nimToCStringConv(colontmpD_);
	{
		NI i_1;
		NU8 b_1;
		NI i_2;
		NI L_1;
		NI T8_;
		i_1 = (NI)0;
		b_1 = (NU8)0;
		nimlf_(182, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");		i_2 = ((NI)0);
		nimln_(183);		T8_ = decompressed_1.len;
		L_1 = T8_;
		{
			nimln_(184);			while (1) {
				if (!(i_2 < L_1)) goto LA10;
				nimlf_(159, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");				i_1 = i_2;
				if (i_2 < 0 || i_2 >= decompressed_1.len){ raiseIndexError2(i_2,decompressed_1.len-1); goto LA1_;
				}
				b_1 = decompressed_1.p->data[i_2];
				nimln_(160);				if ((((NI) (b_1))) < ((NI)0) || (((NI) (b_1))) > ((NI)255)){ raiseRangeErrorI(((NI) (b_1)), ((NI)0), ((NI)255)); goto LA1_;
				}
				result[i_1] = ((NIM_CHAR) ((((NI) (b_1)))));
				nimlf_(13, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators.nim");				i_2 += ((NI)1);
				nimln_(187);				{
					NI T13_;
					T13_ = decompressed_1.len;
					if (!!((T13_ == L_1))) goto LA14_;
					failedAssertImpl__stdZassertions_u95(TM__KQgpv7UNmU0GotFZvsDdZQ_25);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
LA14_: ;
			} LA10: ;
		}
	}
	{
		LA1_:;
	}
	{
		nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		nimln_(651);		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, gzip_decompress_len)(NCSTRING data_p0, int len_p1) {
	int result;
	NimStringV2 s_1;
	NimStringV2 decoded_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_1;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ decompressed_1;
	NimStringV2 blitTmp_1;
	NI T6_;
NIM_BOOL* nimErr_;
	nimfr_("gzip_decompress_len", "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	s_1.len = 0; s_1.p = NIM_NIL;
	decoded_1.len = 0; decoded_1.p = NIM_NIL;
	bytes_1.len = 0; bytes_1.p = NIM_NIL;
	decompressed_1.len = 0; decompressed_1.p = NIM_NIL;
	nimlf_(163, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	s_1 = cstrToString__vools95encoding_u159(data_p0, len_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(164);	{
		if (!(s_1.len == ((NI)0))) goto LA4_;
		nimln_(165);		result = ((int)0);
		nimln_(166);		nimlf_(651, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(167, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decoded_1 = decode__pureZbase64_u500(s_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(168);	blitTmp_1 = decoded_1;
	nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	eqwasMoved___system_u2720((&decoded_1));
	bytes_1 = (*(tySequence__6H5Oh5UUvVCLiakt9aTwtUQ*) (&blitTmp_1));
	nimlf_(169, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_encoding.nim");	decompressed_1 = rleDecompress__vools95encoding_u259(((bytes_1).p) ? (bytes_1.p->data) : NIM_NIL, bytes_1.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(170);	T6_ = decompressed_1.len;
	if ((T6_) < ((int)(-2147483647 -1)) || (T6_) > ((int)2147483647)){ raiseRangeErrorI(T6_, ((int)(-2147483647 -1)), ((int)2147483647)); goto LA1_;
	}
	result = ((int) (T6_));
	{
		LA1_:;
	}
	{
		nimlf_(651, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");		eqdestroy___vools95encoding_u120(decompressed_1);
		eqdestroy___vools95encoding_u120(bytes_1);
		nimln_(394);		if (decoded_1.p && !(decoded_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(decoded_1.p);
}
		if (s_1.p && !(s_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(s_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_EXPORT N_CDECL(void, NimDestroyGlobals)(void) {
}

N_LIB_PRIVATE void PreMainInner(void) {
	atpstdatssynciodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	atpsystemdotnim_Init000();
	(*inner)();
#else
	atpsystemdotnim_Init000();
	PreMainInner();
#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
#else
	PreMain();
	NimMainInner();
#endif
}

BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fwdreason, 
                    LPVOID lpvReserved) {
	if (fwdreason == DLL_PROCESS_ATTACH) {
	NimMain();
	}
	return 1;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}

