/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@palgorithm.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@palgorithm.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA tySequence__Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NI x_p0, NI y_p1, void* ClE_0);
void* ClE_0;
} tyProc__EGDHMEKq2nFyDlkU6lrC3A;
typedef NU8 tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_7) (NI x_p0, NI y_p1);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_12) (NI x_p0, NI y_p1);
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NF x_p0, NF y_p1, void* ClE_0);
void* ClE_0;
} tyProc__NZqIkqSMP3O9a1sEjf9bp1vg;
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA {
  NI len; tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content* p;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_27) (NF x_p0, NF y_p1);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_31) (NF x_p0, NF y_p1);
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NimStringV2 x_p0, NimStringV2 y_p1, void* ClE_0);
void* ClE_0;
} tyProc__3pmh9bG9bLpdxUjFu9cDtbZaA;
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_46) (NimStringV2 x_p0, NimStringV2 y_p1);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_50) (NimStringV2 x_p0, NimStringV2 y_p1);
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE]; };
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content { NI cap; NF data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, newSeq__vools95seq_u490)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u646)(NI* a_p0, NI a_p0Len_0, NI* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__EGDHMEKq2nFyDlkU6lrC3A cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6);
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u8644)(NI* dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u64)(tySequence__qwqHTkRvwhrRyENtudHQ7g dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__Zj5xKXgsXnI4n4hPS6nACA, newSeq__vools95seq_u1573)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u1777)(NF* a_p0, NI a_p0Len_0, NF* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__NZqIkqSMP3O9a1sEjf9bp1vg cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u218)(tySequence__Zj5xKXgsXnI4n4hPS6nACA dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, newSeq__stdZsyncio_u656)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u2026)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__3pmh9bG9bLpdxUjFu9cDtbZaA cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2729)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2720)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5608)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ dest_p0);
static const struct {
  NI cap; NIM_CHAR data[78+1];
} TM__JdC9c6SaUkvO1XjYuWP1JWQ_8 = { 78 | NIM_STRLIT_FLAG, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim(338, 3) `j <= m` " };
static const NimStringV2 TM__JdC9c6SaUkvO1XjYuWP1JWQ_9 = {78, (NimStrPayload*)&TM__JdC9c6SaUkvO1XjYuWP1JWQ_8};
static const NimStringV2 TM__JdC9c6SaUkvO1XjYuWP1JWQ_28 = {78, (NimStrPayload*)&TM__JdC9c6SaUkvO1XjYuWP1JWQ_8};
static const NimStringV2 TM__JdC9c6SaUkvO1XjYuWP1JWQ_47 = {78, (NimStrPayload*)&TM__JdC9c6SaUkvO1XjYuWP1JWQ_8};
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p1) {
	NI result;
	NI y_1;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_4;
	NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_5;
	nimfr_("*", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{	result = (NI)0;
	nimlf_(68, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");	if (nimSubInt(order_p1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_4)) { raiseOverflow(); goto BeforeRet_;
	};
	y_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_4);
	nimln_(69);	if (nimSubInt((NI)(x_p0 ^ y_1), y_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_5)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u646)(NI* a_p0, NI a_p0Len_0, NI* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__EGDHMEKq2nFyDlkU6lrC3A cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
	nimfr_("mergeAlt", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	nimln_(335);	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_6;
		NI T3_;
		NI T4_;
		if (m_p3 < 0 || m_p3 >= a_p0Len_0){ raiseIndexError2(m_p3,a_p0Len_0-1); goto BeforeRet_;
		}
		if (nimAddInt(m_p3, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_6)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6) < 0 || (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6) >= a_p0Len_0){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6),a_p0Len_0-1); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6)], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_7)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_6)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(336);	j_1 = lo_p2;
	nimln_(338);	{
		if (!!((j_1 <= m_p3))) goto LA9_;
		failedAssertImpl__stdZassertions_u95(TM__JdC9c6SaUkvO1XjYuWP1JWQ_9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	nimln_(340);	bb_1 = ((NI)0);
	{
		nimln_(341);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_10;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_11;
			if (!(j_1 <= m_p3)) goto LA12;
			nimln_(323);			if (bb_1 < 0 || bb_1 >= b_p1Len_0){ raiseIndexError2(bb_1,b_p1Len_0-1); goto BeforeRet_;
			}
			if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
			}
			b_p1[bb_1] = a_p0[j_1];
			eqwasMoved___system_u8644((&a_p0[j_1]));
			nimln_(343);			if (nimAddInt(bb_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_10)) { raiseOverflow(); goto BeforeRet_;
			};
			bb_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_10);
			nimln_(344);			if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_11)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_11);
		} LA12: ;
	}
	nimln_(348);	i_1 = ((NI)0);
	nimln_(349);	k_1 = lo_p2;
	{
		nimln_(351);		while (1) {
			NIM_BOOL T15_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_15;
			T15_ = (NIM_BOOL)0;
			T15_ = (k_1 < j_1);
			if (!(T15_)) goto LA16_;
			T15_ = (j_1 <= hi_p4);
LA16_: ;
			if (!T15_) goto LA14;
			nimln_(352);			{
				NI T19_;
				NI T20_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_13;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T19_ = (NI)0;
				T19_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_12)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T20_ = (NI)0;
				T20_ = star___pureZalgorithm_u8(T19_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T20_ <= ((NI)0))) goto LA21_;
				nimln_(323);				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				a_p0[k_1] = b_p1[i_1];
				eqwasMoved___system_u8644((&b_p1[i_1]));
				nimln_(354);				if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_13)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_13);
			}
			goto LA17_;
LA21_: ;
			{
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_14;
				nimln_(323);				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				a_p0[k_1] = a_p0[j_1];
				eqwasMoved___system_u8644((&a_p0[j_1]));
				nimln_(357);				if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_14)) { raiseOverflow(); goto BeforeRet_;
				};
				j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_14);
			}
LA17_: ;
			nimln_(358);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_15)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_15);
		} LA14: ;
	}
	{
		nimln_(361);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_16;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_17;
			if (!(k_1 < j_1)) goto LA25;
			nimln_(323);			if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
			}
			if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
			}
			a_p0[k_1] = b_p1[i_1];
			eqwasMoved___system_u8644((&b_p1[i_1]));
			nimln_(363);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_16)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_16);
			nimln_(364);			if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_17)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_17);
		} LA25: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sort__vools95seq_u599)(NI* a_p0, NI a_p0Len_0, tyProc__EGDHMEKq2nFyDlkU6lrC3A cmp_p1, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p2) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
	nimfr_("sort", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	nimln_(411);	n_1 = a_p0Len_0;
	nimln_(412);	if (((NI)((n_1) / (((NI)2)))) < ((NI)0) || ((NI)((n_1) / (((NI)2)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_1) / (((NI)2))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	b_1 = newSeq__vools95seq_u490(((NI)((n_1) / (((NI)2)))));
	nimln_(413);	s_1 = ((NI)1);
	{
		nimln_(414);		while (1) {
			NI m_1;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_2;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_3;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_23;
			if (!(s_1 < n_1)) goto LA2;
			nimln_(415);			if (nimSubInt(n_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_2), s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_3)) { raiseOverflow(); goto BeforeRet_;
			};
			m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_3);
			{
				nimln_(416);				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_18;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_19;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_20;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_21;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_22;
					if (!(((NI)0) <= m_1)) goto LA4;
					nimln_(417);					if (nimSubInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_18)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_18), ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_19)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_20)) { raiseOverflow(); goto BeforeRet_;
					};
					mergeAlt__vools95seq_u646(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_19) >= ((NI)0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_19) : ((NI)0)), m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_20), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(418);					if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_21)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_21), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_22)) { raiseOverflow(); goto BeforeRet_;
					};
					m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_22);
				} LA4: ;
			}
			nimln_(419);			if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_23)) { raiseOverflow(); goto BeforeRet_;
			};
			s_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_23);
		} LA2: ;
	}
	nimlf_(7, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_seq.nim");	eqdestroy___vools95seq_u64(b_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u1777)(NF* a_p0, NI a_p0Len_0, NF* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__NZqIkqSMP3O9a1sEjf9bp1vg cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
	nimfr_("mergeAlt", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(335, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_26;
		NI T3_;
		NI T4_;
		if (m_p3 < 0 || m_p3 >= a_p0Len_0){ raiseIndexError2(m_p3,a_p0Len_0-1); goto BeforeRet_;
		}
		if (nimAddInt(m_p3, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_26)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26) < 0 || (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26) >= a_p0Len_0){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26),a_p0Len_0-1); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26)], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_27)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_26)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(336);	j_1 = lo_p2;
	nimln_(338);	{
		if (!!((j_1 <= m_p3))) goto LA9_;
		failedAssertImpl__stdZassertions_u95(TM__JdC9c6SaUkvO1XjYuWP1JWQ_28);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	nimln_(340);	bb_1 = ((NI)0);
	{
		nimln_(341);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_29;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_30;
			if (!(j_1 <= m_p3)) goto LA12;
			nimln_(323);			if (bb_1 < 0 || bb_1 >= b_p1Len_0){ raiseIndexError2(bb_1,b_p1Len_0-1); goto BeforeRet_;
			}
			if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
			}
			b_p1[bb_1] = a_p0[j_1];
			a_p0[j_1] = 0;
			nimln_(343);			if (nimAddInt(bb_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_29)) { raiseOverflow(); goto BeforeRet_;
			};
			bb_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_29);
			nimln_(344);			if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_30)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_30);
		} LA12: ;
	}
	nimln_(348);	i_1 = ((NI)0);
	nimln_(349);	k_1 = lo_p2;
	{
		nimln_(351);		while (1) {
			NIM_BOOL T15_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_34;
			T15_ = (NIM_BOOL)0;
			T15_ = (k_1 < j_1);
			if (!(T15_)) goto LA16_;
			T15_ = (j_1 <= hi_p4);
LA16_: ;
			if (!T15_) goto LA14;
			nimln_(352);			{
				NI T19_;
				NI T20_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_32;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T19_ = (NI)0;
				T19_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_31)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T20_ = (NI)0;
				T20_ = star___pureZalgorithm_u8(T19_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T20_ <= ((NI)0))) goto LA21_;
				nimln_(323);				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				a_p0[k_1] = b_p1[i_1];
				b_p1[i_1] = 0;
				nimln_(354);				if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_32)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_32);
			}
			goto LA17_;
LA21_: ;
			{
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_33;
				nimln_(323);				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				a_p0[k_1] = a_p0[j_1];
				a_p0[j_1] = 0;
				nimln_(357);				if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_33)) { raiseOverflow(); goto BeforeRet_;
				};
				j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_33);
			}
LA17_: ;
			nimln_(358);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_34)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_34);
		} LA14: ;
	}
	{
		nimln_(361);		while (1) {
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_35;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_36;
			if (!(k_1 < j_1)) goto LA25;
			nimln_(323);			if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
			}
			if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
			}
			a_p0[k_1] = b_p1[i_1];
			b_p1[i_1] = 0;
			nimln_(363);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_35)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_35);
			nimln_(364);			if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_36)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_36);
		} LA25: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sort__vools95seq_u1730)(NF* a_p0, NI a_p0Len_0, tyProc__NZqIkqSMP3O9a1sEjf9bp1vg cmp_p1, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p2) {
	tySequence__Zj5xKXgsXnI4n4hPS6nACA b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
	nimfr_("sort", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	nimln_(411);	n_1 = a_p0Len_0;
	nimln_(412);	if (((NI)((n_1) / (((NI)2)))) < ((NI)0) || ((NI)((n_1) / (((NI)2)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_1) / (((NI)2))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	b_1 = newSeq__vools95seq_u1573(((NI)((n_1) / (((NI)2)))));
	nimln_(413);	s_1 = ((NI)1);
	{
		nimln_(414);		while (1) {
			NI m_1;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_24;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_25;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_42;
			if (!(s_1 < n_1)) goto LA2;
			nimln_(415);			if (nimSubInt(n_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_24)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_24), s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_25)) { raiseOverflow(); goto BeforeRet_;
			};
			m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_25);
			{
				nimln_(416);				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_37;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_38;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_39;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_40;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_41;
					if (!(((NI)0) <= m_1)) goto LA4;
					nimln_(417);					if (nimSubInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_37)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_37), ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_38)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_39)) { raiseOverflow(); goto BeforeRet_;
					};
					mergeAlt__vools95seq_u1777(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_38) >= ((NI)0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_38) : ((NI)0)), m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_39), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(418);					if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_40)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_40), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_41)) { raiseOverflow(); goto BeforeRet_;
					};
					m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_41);
				} LA4: ;
			}
			nimln_(419);			if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_42)) { raiseOverflow(); goto BeforeRet_;
			};
			s_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_42);
		} LA2: ;
	}
	nimlf_(15, "e:\\IDEProjects\\AI\\vools\\nim_core\\vools_seq.nim");	eqdestroy___vools95seq_u218(b_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__vools95seq_u2026)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2* b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__3pmh9bG9bLpdxUjFu9cDtbZaA cmp_p5, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
	nimfr_("mergeAlt", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(335, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");	{
		NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_45;
		NI T3_;
		NI T4_;
		if (m_p3 < 0 || m_p3 >= a_p0Len_0){ raiseIndexError2(m_p3,a_p0Len_0-1); goto BeforeRet_;
		}
		if (nimAddInt(m_p3, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_45)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_45) < 0 || (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_45) >= a_p0Len_0){ raiseIndexError2((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_45),a_p0Len_0-1); goto BeforeRet_;
		}
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_45)], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_46)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_45)]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	nimln_(336);	j_1 = lo_p2;
	nimln_(338);	{
		if (!!((j_1 <= m_p3))) goto LA9_;
		failedAssertImpl__stdZassertions_u95(TM__JdC9c6SaUkvO1XjYuWP1JWQ_47);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	nimln_(340);	bb_1 = ((NI)0);
	{
		nimln_(341);		while (1) {
			NimStringV2 T13_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_48;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_49;
			if (!(j_1 <= m_p3)) goto LA12;
			nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");			if (bb_1 < 0 || bb_1 >= b_p1Len_0){ raiseIndexError2(bb_1,b_p1Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");			if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
			}
			T13_.len = 0; T13_.p = NIM_NIL;
			T13_ = a_p0[j_1];
			eqwasMoved___system_u2720((&a_p0[j_1]));
			nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");			eqsink___system_u2729((&b_p1[bb_1]), T13_);
			nimlf_(343, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");			if (nimAddInt(bb_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_48)) { raiseOverflow(); goto BeforeRet_;
			};
			bb_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_48);
			nimln_(344);			if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_49)) { raiseOverflow(); goto BeforeRet_;
			};
			j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_49);
		} LA12: ;
	}
	nimln_(348);	i_1 = ((NI)0);
	nimln_(349);	k_1 = lo_p2;
	{
		nimln_(351);		while (1) {
			NIM_BOOL T16_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_53;
			T16_ = (NIM_BOOL)0;
			T16_ = (k_1 < j_1);
			if (!(T16_)) goto LA17_;
			T16_ = (j_1 <= hi_p4);
LA17_: ;
			if (!T16_) goto LA15;
			nimln_(352);			{
				NI T20_;
				NI T21_;
				NimStringV2 T24_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_51;
				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T20_ = (NI)0;
				T20_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_50)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T21_ = (NI)0;
				T21_ = star___pureZalgorithm_u8(T20_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T21_ <= ((NI)0))) goto LA22_;
				nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");				if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
				}
				T24_.len = 0; T24_.p = NIM_NIL;
				T24_ = b_p1[i_1];
				eqwasMoved___system_u2720((&b_p1[i_1]));
				nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				eqsink___system_u2729((&a_p0[k_1]), T24_);
				nimlf_(354, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");				if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_51)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_51);
			}
			goto LA18_;
LA22_: ;
			{
				NimStringV2 T26_;
				NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_52;
				nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
				}
				nimlf_(323, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");				if (j_1 < 0 || j_1 >= a_p0Len_0){ raiseIndexError2(j_1,a_p0Len_0-1); goto BeforeRet_;
				}
				T26_.len = 0; T26_.p = NIM_NIL;
				T26_ = a_p0[j_1];
				eqwasMoved___system_u2720((&a_p0[j_1]));
				nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				eqsink___system_u2729((&a_p0[k_1]), T26_);
				nimlf_(357, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");				if (nimAddInt(j_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_52)) { raiseOverflow(); goto BeforeRet_;
				};
				j_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_52);
			}
LA18_: ;
			nimln_(358);			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_53)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_53);
		} LA15: ;
	}
	{
		nimln_(361);		while (1) {
			NimStringV2 T29_;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_54;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_55;
			if (!(k_1 < j_1)) goto LA28;
			nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");			if (k_1 < 0 || k_1 >= a_p0Len_0){ raiseIndexError2(k_1,a_p0Len_0-1); goto BeforeRet_;
			}
			nimlf_(323, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");			if (i_1 < 0 || i_1 >= b_p1Len_0){ raiseIndexError2(i_1,b_p1Len_0-1); goto BeforeRet_;
			}
			T29_.len = 0; T29_.p = NIM_NIL;
			T29_ = b_p1[i_1];
			eqwasMoved___system_u2720((&b_p1[i_1]));
			nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");			eqsink___system_u2729((&a_p0[k_1]), T29_);
			nimlf_(363, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");			if (nimAddInt(k_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_54)) { raiseOverflow(); goto BeforeRet_;
			};
			k_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_54);
			nimln_(364);			if (nimAddInt(i_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_55)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_55);
		} LA28: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, sort__vools95seq_u1979)(NimStringV2* a_p0, NI a_p0Len_0, tyProc__3pmh9bG9bLpdxUjFu9cDtbZaA cmp_p1, tyEnum_SortOrder__EcZ9b1jMzzz9bqzoPWLCVOXQ order_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
	nimfr_("sort", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\algorithm.nim");
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	nimln_(411);	n_1 = a_p0Len_0;
	nimln_(412);	if (((NI)((n_1) / (((NI)2)))) < ((NI)0) || ((NI)((n_1) / (((NI)2)))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)((n_1) / (((NI)2))), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	b_1 = newSeq__stdZsyncio_u656(((NI)((n_1) / (((NI)2)))));
	nimln_(413);	s_1 = ((NI)1);
	{
		nimln_(414);		while (1) {
			NI m_1;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_43;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_44;
			NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_61;
			if (!(s_1 < n_1)) goto LA2;
			nimln_(415);			if (nimSubInt(n_1, ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_43)) { raiseOverflow(); goto BeforeRet_;
			};
			if (nimSubInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_43), s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_44)) { raiseOverflow(); goto BeforeRet_;
			};
			m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_44);
			{
				nimln_(416);				while (1) {
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_56;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_57;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_58;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_59;
					NI TM__JdC9c6SaUkvO1XjYuWP1JWQ_60;
					if (!(((NI)0) <= m_1)) goto LA4;
					nimln_(417);					if (nimSubInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_56)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_56), ((NI)1), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_57)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimAddInt(m_1, s_1, &TM__JdC9c6SaUkvO1XjYuWP1JWQ_58)) { raiseOverflow(); goto BeforeRet_;
					};
					mergeAlt__vools95seq_u2026(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_57) >= ((NI)0)) ? (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_57) : ((NI)0)), m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_58), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(418);					if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_59)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt(m_1, (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_59), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_60)) { raiseOverflow(); goto BeforeRet_;
					};
					m_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_60);
				} LA4: ;
			}
			nimln_(419);			if (nimMulInt(s_1, ((NI)2), &TM__JdC9c6SaUkvO1XjYuWP1JWQ_61)) { raiseOverflow(); goto BeforeRet_;
			};
			s_1 = (NI)(TM__JdC9c6SaUkvO1XjYuWP1JWQ_61);
		} LA2: ;
	}
	nimlf_(2219, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	eqdestroy___system_u5608(b_1);
	}BeforeRet_: ;
	popFrame();
}
