/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@pbase64.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@pbase64.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA;
typedef struct tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__cjOqO0U2d5cxd8MvHBESIw tySequence__cjOqO0U2d5cxd8MvHBESIw;
typedef struct tySequence__cjOqO0U2d5cxd8MvHBESIw_Content tySequence__cjOqO0U2d5cxd8MvHBESIw_Content;
typedef struct tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NIM_CHAR tyArray__o9aRz9a9a9bzfUdxgetJHLgorg[64];
typedef NIM_CHAR tyArray__bErjiHmvISNmC2iIqkq21Q[256];
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__cjOqO0U2d5cxd8MvHBESIw {
  NI len; tySequence__cjOqO0U2d5cxd8MvHBESIw_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__cjOqO0U2d5cxd8MvHBESIw trace;
	Exception* up;
};
struct tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA {
	Exception Sup;
};
struct tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA {
	tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA Sup;
};
struct tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__cjOqO0U2d5cxd8MvHBESIw_Content { NI cap; tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2462)(NimStringV2* s_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, decodeSize__pureZbase64_u503)(NI size_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorU)(NU64 i_p0, NU64 a_p1, NU64 b_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_44 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_45 = {0, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_44};
extern TNimTypeV2 NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_;
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_52 = { 33 | NIM_STRLIT_FLAG, "Invalid base64 format character `" };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_53 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_54 = { 7 | NIM_STRLIT_FLAG, "` (ord " };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_55 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_56 = { 14 | NIM_STRLIT_FLAG, ") at location " };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_57 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__2L6xrRPz7CWDB3T1R9cDN5A_58 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_59 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_61 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_62 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_63 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_64 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_66 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_67 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_68 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_69 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_71 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_72 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_73 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_74 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_80 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_81 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_82 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_83 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_85 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_86 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_87 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_88 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_91 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_92 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_93 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_94 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_96 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_97 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_98 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_99 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_101 = {33, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_52};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_102 = {7, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_54};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_103 = {14, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_56};
static const NimStringV2 TM__2L6xrRPz7CWDB3T1R9cDN5A_104 = {1, (NimStrPayload*)&TM__2L6xrRPz7CWDB3T1R9cDN5A_58};
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64safe__pureZbase64_u5 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
45,
95}
;
N_LIB_PRIVATE NIM_CONST tyArray__o9aRz9a9a9bzfUdxgetJHLgorg cb64__pureZbase64_u4 = {65,
66,
67,
68,
69,
70,
71,
72,
73,
74,
75,
76,
77,
78,
79,
80,
81,
82,
83,
84,
85,
86,
87,
88,
89,
90,
97,
98,
99,
100,
101,
102,
103,
104,
105,
106,
107,
108,
109,
110,
111,
112,
113,
114,
115,
116,
117,
118,
119,
120,
121,
122,
48,
49,
50,
51,
52,
53,
54,
55,
56,
57,
43,
47}
;
N_LIB_PRIVATE NIM_CONST tyArray__bErjiHmvISNmC2iIqkq21Q decodeTable__pureZbase64_u499 = {255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
62,
255,
62,
255,
63,
52,
53,
54,
55,
56,
57,
58,
59,
60,
61,
255,
255,
255,
255,
255,
255,
255,
0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
20,
21,
22,
23,
24,
25,
255,
255,
255,
255,
63,
255,
26,
27,
28,
29,
30,
31,
32,
33,
34,
35,
36,
37,
38,
39,
40,
41,
42,
43,
44,
45,
46,
47,
48,
49,
50,
51,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255,
255}
;
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2462(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, encode__vools95encoding_u329)(NU8* s_p0, NI s_p0Len_0, NIM_BOOL safe_p1) {
	NimStringV2 result;
	nimfr_("encode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimlf_(154, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");	{
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_2;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_3;
		NI paddingX60gensym1__1;
		NI inputEndsX60gensym1__1;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_4;
		NI inputIndexX60gensym1__1;
		NI outputIndexX60gensym1__1;
		NU32 nX60gensym1__1;
		NU32 bX60gensym1__1;
		if (!safe_p1) goto LA3_;
		nimln_(81);		nimln_(76);		nimln_(81);		if (nimAddInt((NI)((s_p0Len_0) / (((NI)3))), s_p0Len_0, &TM__2L6xrRPz7CWDB3T1R9cDN5A_2)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_2), ((NI)6), &TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) < ((NI)0) || ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_3)));
		nimln_(84);		paddingX60gensym1__1 = (NI)((s_p0Len_0) % (((NI)3)));
		nimln_(85);		if (nimSubInt(s_p0Len_0, paddingX60gensym1__1, &TM__2L6xrRPz7CWDB3T1R9cDN5A_4)) { raiseOverflow(); goto BeforeRet_;
		};
		inputEndsX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_4);
		nimln_(88);		inputIndexX60gensym1__1 = ((NI)0);
		nimln_(89);		outputIndexX60gensym1__1 = ((NI)0);
		nX60gensym1__1 = (NU32)0;
		bX60gensym1__1 = (NU32)0;
		{
			nimln_(106);			while (1) {
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_5;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_6;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_7;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_8;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_9;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_10;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_11;
				if (!!((inputIndexX60gensym1__1 == inputEndsX60gensym1__1))) goto LA6;
				nimln_(94);				if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
				nimln_(95);				nimln_(107);				nX60gensym1__1 = (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)16) & (32 - 1)));
				if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_5)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_5);
				nimln_(94);				if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
				nimln_(95);				nimln_(108);				nX60gensym1__1 = (NU32)(nX60gensym1__1 | (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)8) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_6)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_6);
				nimln_(94);				if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
				nimln_(95);				nimln_(109);				nX60gensym1__1 = (NU32)(nX60gensym1__1 | (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)0) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_7)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_7);
				nimln_(99);				if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(110);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_8)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_8);
				nimln_(99);				if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(111);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_9)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_9);
				nimln_(99);				if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(112);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_10)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_10);
				nimln_(99);				if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(113);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_11)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_11);
			} LA6: ;
		}
		nimln_(115);		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_12;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_13;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_14;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_15;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_16;
			if (!(paddingX60gensym1__1 == ((NI)1))) goto LA9_;
			nimln_(94);			if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
			nimln_(95);			nimln_(116);			nX60gensym1__1 = (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_12)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_12);
			nimln_(99);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(117);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_13)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_13);
			nimln_(99);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(118);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_14)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_14);
			nimln_(103);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(119);			result.p->data[outputIndexX60gensym1__1] = 61;
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_15)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_15);
			nimln_(103);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(120);			result.p->data[outputIndexX60gensym1__1] = 61;
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_16)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_16);
		}
		goto LA7_;
LA9_: ;
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_17;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_18;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_19;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_20;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_21;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_22;
			nimln_(122);			if (!(paddingX60gensym1__1 == ((NI)2))) goto LA12_;
			nimln_(94);			if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
			nimln_(95);			nimln_(123);			nX60gensym1__1 = (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_17)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_17);
			nimln_(94);			if (inputIndexX60gensym1__1 < 0 || inputIndexX60gensym1__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym1__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym1__1 = ((NU32) (s_p0[inputIndexX60gensym1__1]));
			nimln_(95);			nimln_(124);			nX60gensym1__1 = (NU32)(nX60gensym1__1 | (NU32)((NU64)(bX60gensym1__1) << (NU64)(((NI)8) & (32 - 1))));
			if (nimAddInt(inputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_18)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_18);
			nimln_(99);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(125);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_19)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_19);
			nimln_(99);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(126);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_20)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_20);
			nimln_(99);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(127);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym1__1] = cb64safe__pureZbase64_u5[((NU32)((NU32)((NU32)(nX60gensym1__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_21)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_21);
			nimln_(103);			if (outputIndexX60gensym1__1 < 0 || outputIndexX60gensym1__1 >= result.len){ raiseIndexError2(outputIndexX60gensym1__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(128);			result.p->data[outputIndexX60gensym1__1] = 61;
			if (nimAddInt(outputIndexX60gensym1__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_22)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym1__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_22);
		}
		goto LA7_;
LA12_: ;
LA7_: ;
		nimln_(130);		if ((outputIndexX60gensym1__1) < ((NI)0) || (outputIndexX60gensym1__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outputIndexX60gensym1__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (outputIndexX60gensym1__1));
	}
	goto LA1_;
LA3_: ;
	{
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_23;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_24;
		NI paddingX60gensym34__1;
		NI inputEndsX60gensym34__1;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_25;
		NI inputIndexX60gensym34__1;
		NI outputIndexX60gensym34__1;
		NU32 nX60gensym34__1;
		NU32 bX60gensym34__1;
		nimln_(81);		nimln_(76);		nimln_(81);		if (nimAddInt((NI)((s_p0Len_0) / (((NI)3))), s_p0Len_0, &TM__2L6xrRPz7CWDB3T1R9cDN5A_23)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimAddInt((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_23), ((NI)6), &TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) < ((NI)0) || ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_24)));
		nimln_(84);		paddingX60gensym34__1 = (NI)((s_p0Len_0) % (((NI)3)));
		nimln_(85);		if (nimSubInt(s_p0Len_0, paddingX60gensym34__1, &TM__2L6xrRPz7CWDB3T1R9cDN5A_25)) { raiseOverflow(); goto BeforeRet_;
		};
		inputEndsX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_25);
		nimln_(88);		inputIndexX60gensym34__1 = ((NI)0);
		nimln_(89);		outputIndexX60gensym34__1 = ((NI)0);
		nX60gensym34__1 = (NU32)0;
		bX60gensym34__1 = (NU32)0;
		{
			nimln_(106);			while (1) {
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_26;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_27;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_28;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_29;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_30;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_31;
				NI TM__2L6xrRPz7CWDB3T1R9cDN5A_32;
				if (!!((inputIndexX60gensym34__1 == inputEndsX60gensym34__1))) goto LA16;
				nimln_(94);				if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
				nimln_(95);				nimln_(107);				nX60gensym34__1 = (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)16) & (32 - 1)));
				if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_26)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_26);
				nimln_(94);				if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
				nimln_(95);				nimln_(108);				nX60gensym34__1 = (NU32)(nX60gensym34__1 | (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)8) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_27)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_27);
				nimln_(94);				if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
				}
				bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
				nimln_(95);				nimln_(109);				nX60gensym34__1 = (NU32)(nX60gensym34__1 | (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)0) & (32 - 1))));
				if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_28)) { raiseOverflow(); goto BeforeRet_;
				};
				inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_28);
				nimln_(99);				if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(110);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_29)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_29);
				nimln_(99);				if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(111);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_30)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_30);
				nimln_(99);				if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(112);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_31)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_31);
				nimln_(99);				if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
				}
				nimPrepareStrMutationV2((&result));
				nimln_(113);				if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
				}
				result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)0) & (32 - 1))) & ((NU32)63)))- 0];
				if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_32)) { raiseOverflow(); goto BeforeRet_;
				};
				outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_32);
			} LA16: ;
		}
		nimln_(115);		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_33;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_34;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_35;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_36;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_37;
			if (!(paddingX60gensym34__1 == ((NI)1))) goto LA19_;
			nimln_(94);			if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
			nimln_(95);			nimln_(116);			nX60gensym34__1 = (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_33)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_33);
			nimln_(99);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(117);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_34)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_34);
			nimln_(99);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(118);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_35)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_35);
			nimln_(103);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(119);			result.p->data[outputIndexX60gensym34__1] = 61;
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_36)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_36);
			nimln_(103);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(120);			result.p->data[outputIndexX60gensym34__1] = 61;
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_37)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_37);
		}
		goto LA17_;
LA19_: ;
		{
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_38;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_39;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_40;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_41;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_42;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_43;
			nimln_(122);			if (!(paddingX60gensym34__1 == ((NI)2))) goto LA22_;
			nimln_(94);			if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
			nimln_(95);			nimln_(123);			nX60gensym34__1 = (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)16) & (32 - 1)));
			if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_38)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_38);
			nimln_(94);			if (inputIndexX60gensym34__1 < 0 || inputIndexX60gensym34__1 >= s_p0Len_0){ raiseIndexError2(inputIndexX60gensym34__1,s_p0Len_0-1); goto BeforeRet_;
			}
			bX60gensym34__1 = ((NU32) (s_p0[inputIndexX60gensym34__1]));
			nimln_(95);			nimln_(124);			nX60gensym34__1 = (NU32)(nX60gensym34__1 | (NU32)((NU64)(bX60gensym34__1) << (NU64)(((NI)8) & (32 - 1))));
			if (nimAddInt(inputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_39)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_39);
			nimln_(99);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(125);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)18) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_40)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_40);
			nimln_(99);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(126);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)12) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_41)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_41);
			nimln_(99);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(127);			if ((NU)((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63))) > (NU)(63)){ raiseIndexError2((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)), 63); goto BeforeRet_;
			}
			result.p->data[outputIndexX60gensym34__1] = cb64__pureZbase64_u4[((NU32)((NU32)((NU32)(nX60gensym34__1) >> (NU64)(((NI)6) & (32 - 1))) & ((NU32)63)))- 0];
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_42)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_42);
			nimln_(103);			if (outputIndexX60gensym34__1 < 0 || outputIndexX60gensym34__1 >= result.len){ raiseIndexError2(outputIndexX60gensym34__1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(128);			result.p->data[outputIndexX60gensym34__1] = 61;
			if (nimAddInt(outputIndexX60gensym34__1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_43)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndexX60gensym34__1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_43);
		}
		goto LA17_;
LA22_: ;
LA17_: ;
		nimln_(130);		if ((outputIndexX60gensym34__1) < ((NI)0) || (outputIndexX60gensym34__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outputIndexX60gensym34__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (outputIndexX60gensym34__1));
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, decodeSize__pureZbase64_u503)(NI size_p0) {
	NI result;
	NI TM__2L6xrRPz7CWDB3T1R9cDN5A_46;
	NI TM__2L6xrRPz7CWDB3T1R9cDN5A_47;
	nimfr_("decodeSize", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");
{	result = (NI)0;
	nimln_(227);	nimln_(226);	nimln_(227);	if (nimMulInt(size_p0, ((NI)3), &TM__2L6xrRPz7CWDB3T1R9cDN5A_46)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_46)) / (((NI)4))), ((NI)6), &TM__2L6xrRPz7CWDB3T1R9cDN5A_47)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_47);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1755)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1755(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	(*dest_p0).len += ((NI)1);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, decode__pureZbase64_u500)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI T5_;
	NI inputIndex_1;
	NI outputIndex_1;
	NI inputLen_1;
	NI inputEnds_1;
	NI TM__2L6xrRPz7CWDB3T1R9cDN5A_50;
	NI leftLen_1;
	NI TM__2L6xrRPz7CWDB3T1R9cDN5A_79;
NIM_BOOL* nimErr_;
	nimfr_("decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");
{nimErr_ = nimErrorFlag();
	nimln_(223);	result = TM__2L6xrRPz7CWDB3T1R9cDN5A_45;
	nimln_(224);	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(242);	T5_ = (NI)0;
	T5_ = decodeSize__pureZbase64_u503(s_p0.len);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if ((T5_) < ((NI)0) || (T5_) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(T5_, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&result), (T5_));
	nimln_(244);	inputIndex_1 = ((NI)0);
	nimln_(245);	outputIndex_1 = ((NI)0);
	nimln_(246);	inputLen_1 = s_p0.len;
	nimln_(247);	inputEnds_1 = ((NI)0);
	{
		nimln_(249);		while (1) {
			NIM_BOOL T8_;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_48;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_49;
			T8_ = (NIM_BOOL)0;
			T8_ = (((NI)0) < inputLen_1);
			if (!(T8_)) goto LA9_;
			if (nimSubInt(inputLen_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_48)) { raiseOverflow(); goto BeforeRet_;
			};
			if ((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48) < 0 || (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48) >= s_p0.len){ raiseIndexError2((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48),s_p0.len-1); goto BeforeRet_;
			}
			T8_ = (((NU8)(s_p0.p->data[(NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48)])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[(NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48)])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[(NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48)])) == ((NU8)(32)) || ((NU8)(s_p0.p->data[(NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_48)])) == ((NU8)(61)));
LA9_: ;
			if (!T8_) goto LA7;
			nimln_(250);			if (nimSubInt(inputLen_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_49)) { raiseOverflow(); goto BeforeRet_;
			};
			inputLen_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_49);
		} LA7: ;
	}
	nimln_(252);	if (nimSubInt(inputLen_1, ((NI)4), &TM__2L6xrRPz7CWDB3T1R9cDN5A_50)) { raiseOverflow(); goto BeforeRet_;
	};
	inputEnds_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_50);
	{
		nimln_(253);		while (1) {
			NI a_1;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_60;
			NI b_1;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_65;
			NI c_1;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_70;
			NI d_1;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_75;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_76;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_77;
			NI TM__2L6xrRPz7CWDB3T1R9cDN5A_78;
			if (!(inputIndex_1 <= inputEnds_1)) goto LA11;
			{
				nimln_(254);				while (1) {
					NI TM__2L6xrRPz7CWDB3T1R9cDN5A_51;
					if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
					}
					if (!(((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(10)) || ((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(13)) || ((NU8)(s_p0.p->data[inputIndex_1])) == ((NU8)(32)))) goto LA13;
					nimln_(255);					if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_51)) { raiseOverflow(); goto BeforeRet_;
					};
					inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_51);
				} LA13: ;
			}
			nimln_(257);			{
				if (!(inputEnds_1 < inputIndex_1)) goto LA16_;
				nimln_(258);				goto LA10;
			}
LA16_: ;
			nimln_(259);			nimln_(230);			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
			}
			if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
			}
			a_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			nimln_(231);			{
				NimStringV2 colontmpD_;
				NimStringV2 colontmpD__2;
				tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T23_;
				NimStringV2 T24_;
				if (!(a_1 == ((NI)255))) goto LA20_;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				T23_ = NIM_NIL;
				T23_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
				(*T23_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
				(*T23_).Sup.Sup.name = "ValueError";
				nimln_(234);				T24_.len = 0; T24_.p = NIM_NIL;
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA22_;
				}
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA22_;
				}
				colontmpD_ = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				colontmpD__2 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				T24_ = rawNewString(colontmpD_.len + colontmpD__2.len + 56);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_53);
appendChar((&T24_), s_p0.p->data[inputIndex_1]);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_55);
appendString((&T24_), colontmpD_);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_57);
appendString((&T24_), colontmpD__2);
appendString((&T24_), TM__2L6xrRPz7CWDB3T1R9cDN5A_59);
				(*T23_).Sup.Sup.message = T24_;
				(*T23_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				nimln_(232);				raiseExceptionEx((Exception*)T23_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA22_;
				{
					LA22_:;
				}
				{
					nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA20_: ;
			nimlf_(259, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");			if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_60)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_60);
			nimln_(260);			nimln_(230);			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
			}
			if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
			}
			b_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			nimln_(231);			{
				NimStringV2 colontmpD__3;
				NimStringV2 colontmpD__4;
				tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T32_;
				NimStringV2 T33_;
				if (!(b_1 == ((NI)255))) goto LA29_;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				T32_ = NIM_NIL;
				T32_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
				(*T32_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
				(*T32_).Sup.Sup.name = "ValueError";
				nimln_(234);				T33_.len = 0; T33_.p = NIM_NIL;
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA31_;
				}
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA31_;
				}
				colontmpD__3 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				colontmpD__4 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA31_;
				T33_ = rawNewString(colontmpD__3.len + colontmpD__4.len + 56);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_61);
appendChar((&T33_), s_p0.p->data[inputIndex_1]);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_62);
appendString((&T33_), colontmpD__3);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_63);
appendString((&T33_), colontmpD__4);
appendString((&T33_), TM__2L6xrRPz7CWDB3T1R9cDN5A_64);
				(*T32_).Sup.Sup.message = T33_;
				(*T32_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				nimln_(232);				raiseExceptionEx((Exception*)T32_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA31_;
				{
					LA31_:;
				}
				{
					nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA29_: ;
			nimlf_(260, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");			if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_65)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_65);
			nimln_(261);			nimln_(230);			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
			}
			if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
			}
			c_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			nimln_(231);			{
				NimStringV2 colontmpD__5;
				NimStringV2 colontmpD__6;
				tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T41_;
				NimStringV2 T42_;
				if (!(c_1 == ((NI)255))) goto LA38_;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
				T41_ = NIM_NIL;
				T41_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
				(*T41_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
				(*T41_).Sup.Sup.name = "ValueError";
				nimln_(234);				T42_.len = 0; T42_.p = NIM_NIL;
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA40_;
				}
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA40_;
				}
				colontmpD__5 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA40_;
				colontmpD__6 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA40_;
				T42_ = rawNewString(colontmpD__5.len + colontmpD__6.len + 56);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_66);
appendChar((&T42_), s_p0.p->data[inputIndex_1]);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_67);
appendString((&T42_), colontmpD__5);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_68);
appendString((&T42_), colontmpD__6);
appendString((&T42_), TM__2L6xrRPz7CWDB3T1R9cDN5A_69);
				(*T41_).Sup.Sup.message = T42_;
				(*T41_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				nimln_(232);				raiseExceptionEx((Exception*)T41_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA40_;
				{
					LA40_:;
				}
				{
					nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");					if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
					if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA38_: ;
			nimlf_(261, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");			if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_70)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_70);
			nimln_(262);			nimln_(230);			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
			}
			if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
			}
			d_1 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
			nimln_(231);			{
				NimStringV2 colontmpD__7;
				NimStringV2 colontmpD__8;
				tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T50_;
				NimStringV2 T51_;
				if (!(d_1 == ((NI)255))) goto LA47_;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				colontmpD__8.len = 0; colontmpD__8.p = NIM_NIL;
				T50_ = NIM_NIL;
				T50_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
				(*T50_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
				(*T50_).Sup.Sup.name = "ValueError";
				nimln_(234);				T51_.len = 0; T51_.p = NIM_NIL;
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA49_;
				}
				if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA49_;
				}
				colontmpD__7 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
				if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
				colontmpD__8 = dollar___systemZdollars_u14(inputIndex_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA49_;
				T51_ = rawNewString(colontmpD__7.len + colontmpD__8.len + 56);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_71);
appendChar((&T51_), s_p0.p->data[inputIndex_1]);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_72);
appendString((&T51_), colontmpD__7);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_73);
appendString((&T51_), colontmpD__8);
appendString((&T51_), TM__2L6xrRPz7CWDB3T1R9cDN5A_74);
				(*T50_).Sup.Sup.message = T51_;
				(*T50_).Sup.Sup.parent = ((Exception*) NIM_NIL);
				nimln_(232);				raiseExceptionEx((Exception*)T50_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA49_;
				{
					LA49_:;
				}
				{
					nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");					if (colontmpD__8.p && !(colontmpD__8.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__8.p);
}
					if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
LA47_: ;
			nimlf_(262, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");			if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_75)) { raiseOverflow(); goto BeforeRet_;
			};
			inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_75);
			nimln_(238);			if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(263);			if (((NI)((NI)((NI)((NU64)(a_1) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_1) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(a_1) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_1) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(a_1) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_1) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
			}
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_1) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_1) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
			if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_76)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_76);
			nimln_(238);			if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(264);			if (((NI)((NI)((NI)((NU64)(b_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_1) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(b_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_1) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(b_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_1) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
			}
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(b_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_1) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))));
			if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_77)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_77);
			nimln_(238);			if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
			}
			nimPrepareStrMutationV2((&result));
			nimln_(265);			if (((NI)((NI)((NI)((NU64)(c_1) << (NU64)(((NI)6) & (64 - 1))) | (NI)((NI64)(d_1) >> (NU64)(((NI)0) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(c_1) << (NU64)(((NI)6) & (64 - 1))) | (NI)((NI64)(d_1) >> (NU64)(((NI)0) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(c_1) << (NU64)(((NI)6) & (64 - 1))) | (NI)((NI64)(d_1) >> (NU64)(((NI)0) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
			}
			result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(c_1) << (NU64)(((NI)6) & (64 - 1))) | (NI)((NI64)(d_1) >> (NU64)(((NI)0) & (64 - 1)))) & ((NI)255))));
			if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_78)) { raiseOverflow(); goto BeforeRet_;
			};
			outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_78);
		} LA11: ;
	} LA10: ;
	nimln_(267);	if (nimSubInt(inputIndex_1, inputLen_1, &TM__2L6xrRPz7CWDB3T1R9cDN5A_79)) { raiseOverflow(); goto BeforeRet_;
	};
	if ((NI)(((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_79)) % (((NI)4))) == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
	}
	leftLen_1 = ((NI)(((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_79)) % (((NI)4))) > 0? ((NI)(((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_79)) % (((NI)4)))) : -((NI)(((NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_79)) % (((NI)4)))));
	nimln_(268);	{
		NI a_2;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_84;
		NI b_2;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_89;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_90;
		if (!(leftLen_1 == ((NI)2))) goto LA56_;
		nimln_(269);		nimln_(230);		if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
		}
		if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
		}
		a_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		nimln_(231);		{
			NimStringV2 colontmpD__9;
			NimStringV2 colontmpD__10;
			tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T63_;
			NimStringV2 T64_;
			if (!(a_2 == ((NI)255))) goto LA60_;
			colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
			colontmpD__10.len = 0; colontmpD__10.p = NIM_NIL;
			T63_ = NIM_NIL;
			T63_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
			(*T63_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
			(*T63_).Sup.Sup.name = "ValueError";
			nimln_(234);			T64_.len = 0; T64_.p = NIM_NIL;
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA62_;
			}
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA62_;
			}
			colontmpD__9 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			colontmpD__10 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA62_;
			T64_ = rawNewString(colontmpD__9.len + colontmpD__10.len + 56);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_80);
appendChar((&T64_), s_p0.p->data[inputIndex_1]);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_81);
appendString((&T64_), colontmpD__9);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_82);
appendString((&T64_), colontmpD__10);
appendString((&T64_), TM__2L6xrRPz7CWDB3T1R9cDN5A_83);
			(*T63_).Sup.Sup.message = T64_;
			(*T63_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(232);			raiseExceptionEx((Exception*)T63_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA62_;
			{
				LA62_:;
			}
			{
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD__10.p && !(colontmpD__10.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__10.p);
}
				if (colontmpD__9.p && !(colontmpD__9.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__9.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA60_: ;
		nimlf_(269, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");		if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_84)) { raiseOverflow(); goto BeforeRet_;
		};
		inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_84);
		nimln_(270);		nimln_(230);		if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
		}
		if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
		}
		b_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		nimln_(231);		{
			NimStringV2 colontmpD__11;
			NimStringV2 colontmpD__12;
			tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T72_;
			NimStringV2 T73_;
			if (!(b_2 == ((NI)255))) goto LA69_;
			colontmpD__11.len = 0; colontmpD__11.p = NIM_NIL;
			colontmpD__12.len = 0; colontmpD__12.p = NIM_NIL;
			T72_ = NIM_NIL;
			T72_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
			(*T72_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
			(*T72_).Sup.Sup.name = "ValueError";
			nimln_(234);			T73_.len = 0; T73_.p = NIM_NIL;
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA71_;
			}
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA71_;
			}
			colontmpD__11 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
			colontmpD__12 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA71_;
			T73_ = rawNewString(colontmpD__11.len + colontmpD__12.len + 56);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_85);
appendChar((&T73_), s_p0.p->data[inputIndex_1]);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_86);
appendString((&T73_), colontmpD__11);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_87);
appendString((&T73_), colontmpD__12);
appendString((&T73_), TM__2L6xrRPz7CWDB3T1R9cDN5A_88);
			(*T72_).Sup.Sup.message = T73_;
			(*T72_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(232);			raiseExceptionEx((Exception*)T72_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA71_;
			{
				LA71_:;
			}
			{
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD__12.p && !(colontmpD__12.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__12.p);
}
				if (colontmpD__11.p && !(colontmpD__11.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__11.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA69_: ;
		nimlf_(270, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");		if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_89)) { raiseOverflow(); goto BeforeRet_;
		};
		inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_89);
		nimln_(238);		if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		nimln_(271);		if (((NI)((NI)((NI)((NU64)(a_2) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_2) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(a_2) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_2) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(a_2) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_2) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_2) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_2) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
		if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_90)) { raiseOverflow(); goto BeforeRet_;
		};
		outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_90);
	}
	goto LA54_;
LA56_: ;
	{
		NI a_3;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_95;
		NI b_3;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_100;
		NI c_2;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_105;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_106;
		NI TM__2L6xrRPz7CWDB3T1R9cDN5A_107;
		nimln_(272);		if (!(leftLen_1 == ((NI)3))) goto LA77_;
		nimln_(273);		nimln_(230);		if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
		}
		if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
		}
		a_3 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		nimln_(231);		{
			NimStringV2 colontmpD__13;
			NimStringV2 colontmpD__14;
			tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T84_;
			NimStringV2 T85_;
			if (!(a_3 == ((NI)255))) goto LA81_;
			colontmpD__13.len = 0; colontmpD__13.p = NIM_NIL;
			colontmpD__14.len = 0; colontmpD__14.p = NIM_NIL;
			T84_ = NIM_NIL;
			T84_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
			(*T84_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
			(*T84_).Sup.Sup.name = "ValueError";
			nimln_(234);			T85_.len = 0; T85_.p = NIM_NIL;
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA83_;
			}
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA83_;
			}
			colontmpD__13 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA83_;
			colontmpD__14 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA83_;
			T85_ = rawNewString(colontmpD__13.len + colontmpD__14.len + 56);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_91);
appendChar((&T85_), s_p0.p->data[inputIndex_1]);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_92);
appendString((&T85_), colontmpD__13);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_93);
appendString((&T85_), colontmpD__14);
appendString((&T85_), TM__2L6xrRPz7CWDB3T1R9cDN5A_94);
			(*T84_).Sup.Sup.message = T85_;
			(*T84_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(232);			raiseExceptionEx((Exception*)T84_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA83_;
			{
				LA83_:;
			}
			{
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD__14.p && !(colontmpD__14.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__14.p);
}
				if (colontmpD__13.p && !(colontmpD__13.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__13.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA81_: ;
		nimlf_(273, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");		if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_95)) { raiseOverflow(); goto BeforeRet_;
		};
		inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_95);
		nimln_(274);		nimln_(230);		if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
		}
		if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
		}
		b_3 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		nimln_(231);		{
			NimStringV2 colontmpD__15;
			NimStringV2 colontmpD__16;
			tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T93_;
			NimStringV2 T94_;
			if (!(b_3 == ((NI)255))) goto LA90_;
			colontmpD__15.len = 0; colontmpD__15.p = NIM_NIL;
			colontmpD__16.len = 0; colontmpD__16.p = NIM_NIL;
			T93_ = NIM_NIL;
			T93_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
			(*T93_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
			(*T93_).Sup.Sup.name = "ValueError";
			nimln_(234);			T94_.len = 0; T94_.p = NIM_NIL;
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA92_;
			}
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA92_;
			}
			colontmpD__15 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
			colontmpD__16 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA92_;
			T94_ = rawNewString(colontmpD__15.len + colontmpD__16.len + 56);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_96);
appendChar((&T94_), s_p0.p->data[inputIndex_1]);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_97);
appendString((&T94_), colontmpD__15);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_98);
appendString((&T94_), colontmpD__16);
appendString((&T94_), TM__2L6xrRPz7CWDB3T1R9cDN5A_99);
			(*T93_).Sup.Sup.message = T94_;
			(*T93_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(232);			raiseExceptionEx((Exception*)T93_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA92_;
			{
				LA92_:;
			}
			{
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD__16.p && !(colontmpD__16.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__16.p);
}
				if (colontmpD__15.p && !(colontmpD__15.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__15.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA90_: ;
		nimlf_(274, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");		if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_100)) { raiseOverflow(); goto BeforeRet_;
		};
		inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_100);
		nimln_(275);		nimln_(230);		if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto BeforeRet_;
		}
		if ((NU)(((NU8)(s_p0.p->data[inputIndex_1]))) > (NU)(255)){ raiseIndexError2(((NU8)(s_p0.p->data[inputIndex_1])), 255); goto BeforeRet_;
		}
		c_2 = ((NI) (((NU8)(decodeTable__pureZbase64_u499[(((NU8)(s_p0.p->data[inputIndex_1])))- 0]))));
		nimln_(231);		{
			NimStringV2 colontmpD__17;
			NimStringV2 colontmpD__18;
			tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* T102_;
			NimStringV2 T103_;
			if (!(c_2 == ((NI)255))) goto LA99_;
			colontmpD__17.len = 0; colontmpD__17.p = NIM_NIL;
			colontmpD__18.len = 0; colontmpD__18.p = NIM_NIL;
			T102_ = NIM_NIL;
			T102_ = (tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) nimNewObj(sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA));
			(*T102_).Sup.Sup.Sup.m_type = (&NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_);
			(*T102_).Sup.Sup.name = "ValueError";
			nimln_(234);			T103_.len = 0; T103_.p = NIM_NIL;
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA101_;
			}
			if (inputIndex_1 < 0 || inputIndex_1 >= s_p0.len){ raiseIndexError2(inputIndex_1,s_p0.len-1); goto LA101_;
			}
			colontmpD__17 = dollar___systemZdollars_u14(((NU8)(s_p0.p->data[inputIndex_1])));
			if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
			colontmpD__18 = dollar___systemZdollars_u14(inputIndex_1);
			if (NIM_UNLIKELY(*nimErr_)) goto LA101_;
			T103_ = rawNewString(colontmpD__17.len + colontmpD__18.len + 56);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_101);
appendChar((&T103_), s_p0.p->data[inputIndex_1]);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_102);
appendString((&T103_), colontmpD__17);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_103);
appendString((&T103_), colontmpD__18);
appendString((&T103_), TM__2L6xrRPz7CWDB3T1R9cDN5A_104);
			(*T102_).Sup.Sup.message = T103_;
			(*T102_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			nimln_(232);			raiseExceptionEx((Exception*)T102_, "ValueError", "decode", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim", 232);
goto LA101_;
			{
				LA101_:;
			}
			{
				nimlf_(394, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");				if (colontmpD__18.p && !(colontmpD__18.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__18.p);
}
				if (colontmpD__17.p && !(colontmpD__17.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__17.p);
}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA99_: ;
		nimlf_(275, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\base64.nim");		if (nimAddInt(inputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_105)) { raiseOverflow(); goto BeforeRet_;
		};
		inputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_105);
		nimln_(238);		if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		nimln_(276);		if (((NI)((NI)((NI)((NU64)(a_3) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_3) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(a_3) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_3) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(a_3) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_3) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(a_3) << (NU64)(((NI)2) & (64 - 1))) | (NI)((NI64)(b_3) >> (NU64)(((NI)4) & (64 - 1)))) & ((NI)255))));
		if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_106)) { raiseOverflow(); goto BeforeRet_;
		};
		outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_106);
		nimln_(238);		if (outputIndex_1 < 0 || outputIndex_1 >= result.len){ raiseIndexError2(outputIndex_1,result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		nimln_(277);		if (((NI)((NI)((NI)((NU64)(b_3) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_2) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))) < 0 || ((NI)((NI)((NI)((NU64)(b_3) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_2) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))) > 255){ raiseRangeErrorU((NI)((NI)((NI)((NU64)(b_3) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_2) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255)), 0, 255); goto BeforeRet_;
		}
		result.p->data[outputIndex_1] = ((NIM_CHAR) ((NI)((NI)((NI)((NU64)(b_3) << (NU64)(((NI)4) & (64 - 1))) | (NI)((NI64)(c_2) >> (NU64)(((NI)2) & (64 - 1)))) & ((NI)255))));
		if (nimAddInt(outputIndex_1, ((NI)1), &TM__2L6xrRPz7CWDB3T1R9cDN5A_107)) { raiseOverflow(); goto BeforeRet_;
		};
		outputIndex_1 = (NI)(TM__2L6xrRPz7CWDB3T1R9cDN5A_107);
	}
	goto LA54_;
LA77_: ;
LA54_: ;
	nimln_(278);	if ((outputIndex_1) < ((NI)0) || (outputIndex_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(outputIndex_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	setLengthStrV2((&result), (outputIndex_1));
	}BeforeRet_: ;
	popFrame();
	return result;
}
