/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@pmath.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@pmath.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0) {
	NI result;
	result = (NI)0;
	result = (NI)(x_p0 - ((NI)1));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)32) & (64 - 1))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)16) & (64 - 1))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)8) & (64 - 1))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)4) & (64 - 1))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)2) & (64 - 1))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)1) & (64 - 1))));
	result += (NI)(((NI)1) + (x_p0 <= ((NI)0)));
	return result;
}
