/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -IE:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@pparseutils.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@pparseutils.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(NI, parseHex__pureZstrutils_u1002)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1, NI maxLen_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseHex__pureZstrutils_u1002)(NIM_CHAR* s_p0, NI s_p0Len_0, NI* number_p1, NI maxLen_p2) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI i_1;
	NI output_1;
	NIM_BOOL foundDigit_1;
	NI last_1;
	NI T1_;
	nimfr_("parseHex", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\parseutils.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(189, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\parseutils.nim");	i_1 = ((NI)0);
	nimln_(190);	output_1 = ((NI)0);
	nimln_(191);	foundDigit_1 = NIM_FALSE;
	nimln_(192);	T1_ = (NI)0;
	{
		if (!(maxLen_p2 == ((NI)0))) goto LA4_;
		colontmpD_ = s_p0Len_0;
		T1_ = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_2;
		if (nimAddInt(i_1, maxLen_p2, &TM__vI9aZNKIcImom6dDyKXW1ZA_2)) { raiseOverflow(); goto BeforeRet_;
		};
		colontmpD__2 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_2);
		T1_ = colontmpD__2;
	}
LA2_: ;
	last_1 = ((s_p0Len_0 <= T1_) ? s_p0Len_0 : T1_);
	nimln_(193);	{
		NIM_BOOL T9_;
		NIM_BOOL T10_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_3;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_4;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_5;
		T9_ = (NIM_BOOL)0;
		T10_ = (NIM_BOOL)0;
		if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_3)) { raiseOverflow(); goto BeforeRet_;
		};
		T10_ = ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_3) < last_1);
		if (!(T10_)) goto LA11_;
		if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
		}
		T10_ = ((NU8)(s_p0[i_1]) == (NU8)(48));
LA11_: ;
		T9_ = T10_;
		if (!(T9_)) goto LA12_;
		if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_4)) { raiseOverflow(); goto BeforeRet_;
		};
		if ((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4) < 0 || (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4) >= s_p0Len_0){ raiseIndexError2((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4),s_p0Len_0-1); goto BeforeRet_;
		}
		T9_ = (((NU8)(s_p0[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4)])) == ((NU8)(120)) || ((NU8)(s_p0[(NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_4)])) == ((NU8)(88)));
LA12_: ;
		if (!T9_) goto LA13_;
		if (nimAddInt(i_1, ((NI)2), &TM__vI9aZNKIcImom6dDyKXW1ZA_5)) { raiseOverflow(); goto BeforeRet_;
		};
		i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_5);
	}
	goto LA7_;
LA13_: ;
	{
		NIM_BOOL T16_;
		NI TM__vI9aZNKIcImom6dDyKXW1ZA_6;
		nimln_(194);		T16_ = (NIM_BOOL)0;
		T16_ = (i_1 < last_1);
		if (!(T16_)) goto LA17_;
		if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
		}
		T16_ = ((NU8)(s_p0[i_1]) == (NU8)(35));
LA17_: ;
		if (!T16_) goto LA18_;
		if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_6)) { raiseOverflow(); goto BeforeRet_;
		};
		i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_6);
	}
	goto LA7_;
LA18_: ;
LA7_: ;
	{
		nimln_(195);		while (1) {
			NI TM__vI9aZNKIcImom6dDyKXW1ZA_12;
			if (!(i_1 < last_1)) goto LA21;
			nimln_(196);			if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
			}
			switch (((NU8)(s_p0[i_1]))) {
			case 95:
			{
			}
			break;
			case 48 ... 57:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_7;
				nimln_(199);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (nimSubInt(((NU8)(s_p0[i_1])), ((NI)48), &TM__vI9aZNKIcImom6dDyKXW1ZA_7)) { raiseOverflow(); goto BeforeRet_;
				};
				output_1 = (NI)((NI)((NU64)(output_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_7));
				nimln_(200);				foundDigit_1 = NIM_TRUE;
			}
			break;
			case 97 ... 102:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_8;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_9;
				nimln_(202);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (nimSubInt(((NU8)(s_p0[i_1])), ((NI)97), &TM__vI9aZNKIcImom6dDyKXW1ZA_8)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_8), ((NI)10), &TM__vI9aZNKIcImom6dDyKXW1ZA_9)) { raiseOverflow(); goto BeforeRet_;
				};
				output_1 = (NI)((NI)((NU64)(output_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_9));
				nimln_(203);				foundDigit_1 = NIM_TRUE;
			}
			break;
			case 65 ... 70:
			{
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_10;
				NI TM__vI9aZNKIcImom6dDyKXW1ZA_11;
				nimln_(205);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (nimSubInt(((NU8)(s_p0[i_1])), ((NI)65), &TM__vI9aZNKIcImom6dDyKXW1ZA_10)) { raiseOverflow(); goto BeforeRet_;
				};
				if (nimAddInt((NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_10), ((NI)10), &TM__vI9aZNKIcImom6dDyKXW1ZA_11)) { raiseOverflow(); goto BeforeRet_;
				};
				output_1 = (NI)((NI)((NU64)(output_1) << (NU64)(((NI)4) & (64 - 1))) | (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_11));
				nimln_(206);				foundDigit_1 = NIM_TRUE;
			}
			break;
			default:
			{
				nimln_(207);				goto LA20;
			}
			break;
			}
			nimln_(208);			if (nimAddInt(i_1, ((NI)1), &TM__vI9aZNKIcImom6dDyKXW1ZA_12)) { raiseOverflow(); goto BeforeRet_;
			};
			i_1 = (NI)(TM__vI9aZNKIcImom6dDyKXW1ZA_12);
		} LA21: ;
	} LA20: ;
	nimln_(209);	{
		if (!foundDigit_1) goto LA29_;
		nimln_(210);		(*number_p1) = output_1;
		nimln_(211);		result = i_1;
	}
LA29_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parseHex__pureZstrutils_u995)(NimStringV2 s_p0, NI* number_p1, NI start_p2, NI maxLen_p3) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("parseHex", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\parseutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(843);	if ((s_p0.len-1)-start_p2 != -1 && (start_p2 < 0 || start_p2 >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(start_p2, (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	result = parseHex__pureZstrutils_u1002((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(start_p2)) : NIM_NIL), ((s_p0.len-1))-(start_p2)+1, number_p1, maxLen_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
