/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -Ie:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@psets.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@psets.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ tySequence__8Np6tlClE5az1CyqZdN19bQ;
typedef struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content tySequence__8Np6tlClE5az1CyqZdN19bQ_Content;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
struct tySequence__8Np6tlClE5az1CyqZdN19bQ {
  NI len; tySequence__8Np6tlClE5az1CyqZdN19bQ_Content* p;
};
struct tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w {
	tySequence__8Np6tlClE5az1CyqZdN19bQ data;
	NI counter;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
	NI Field0;
	NI Field1;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
struct tySequence__8Np6tlClE5az1CyqZdN19bQ_Content { NI cap; tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE]; };
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w, initHashSet__vools95seq_u841)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, init__vools95seq_u855)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0, NI initialSize_p1);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u249)(NI x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__vools95seq_u871)(tySequence__8Np6tlClE5az1CyqZdN19bQ* s_p0, NI len_p1);
static N_INLINE(NI, rawGet__vools95seq_u1042)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0, NI key_p1, NI* hc_p2);
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0);
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0);
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1);
static N_INLINE(NIM_BOOL, mustRehash__vools95seq_u1183)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u95)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__vools95seq_u1257)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0);
static N_INLINE(NI, rawGetKnownHC__vools95seq_u1309)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0, NI key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__vools95seq_u1366)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ* data_p1, NI key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u951)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u2360)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A, initHashSet__vools95seq_u2207)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, init__vools95seq_u2221)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0, NI initialSize_p1);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__vools95seq_u2237)(tySequence__4eRCaZmrYLLw2k30GPTiMw* s_p0, NI len_p1);
static N_INLINE(NI, rawGet__vools95seq_u2455)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u586)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NIM_BOOL, mustRehash__vools95seq_u2596)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__vools95seq_u2670)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0);
static N_INLINE(NI, rawGetKnownHC__vools95seq_u2722)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__vools95seq_u2779)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2723)(NimStringV2* dest_p0, NimStringV2 src_p1);
static const struct {
  NI cap; NIM_CHAR data[106+1];
} TM__0JXiWyhP5OCO8jWMA6sb1w_6 = { 106 | NIM_STRLIT_FLAG, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_7 = {106, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_6};
static const NimStringV2 TM__0JXiWyhP5OCO8jWMA6sb1w_17 = {106, (NimStrPayload*)&TM__0JXiWyhP5OCO8jWMA6sb1w_6};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
static N_INLINE(void, nimSetMem__system_u2188)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
	nimSetMem__system_u2188(p_p0, ((int)0), size_p1);
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
	NI result;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_2;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_3;
NIM_BOOL* nimErr_;
	nimfr_("slotsNeeded", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(39, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");	if (nimAddInt((NI)((count_p0) / (((NI)2))), count_p0, &TM__0JXiWyhP5OCO8jWMA6sb1w_2)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimAddInt((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_2), ((NI)4), &TM__0JXiWyhP5OCO8jWMA6sb1w_3)) { raiseOverflow(); goto BeforeRet_;
	};
	result = nextPowerOfTwo__pureZmath_u249((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_3));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, init__vools95seq_u855)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym10__1;
NIM_BOOL* nimErr_;
	nimfr_("init", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(19, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	if ((initialSize_p1) < ((NI)0) || (initialSize_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym10__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(23);	(*s_p0).counter = ((NI)0);
	nimlf_(115, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	if ((correctSizeX60gensym10__1) < ((NI)0) || (correctSizeX60gensym10__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym10__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__vools95seq_u871((&(*s_p0).data), (correctSizeX60gensym10__1));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w, initHashSet__vools95seq_u841)(NI initialSize_p0) {
	tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w result;
NIM_BOOL* nimErr_;
	nimfr_("initHashSet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(134);	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w));
	nimln_(135);	init__vools95seq_u855((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w, initSet__vools95seq_u828)(NI initialSize_p0) {
	tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w result;
NIM_BOOL* nimErr_;
	nimfr_("initSet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w));
	nimln_(605);	result = initHashSet__vools95seq_u841(initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1) {
	NU64 result;
	nimfr_("hiXorLo", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\hashes.nim");
	result = (NU64)0;
	nimlf_(125, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\hashes.nim");	result = 0ULL;
	nimln_(126);	__uint128_t r = a_p0; r *= b_p1; result = (r >> 64) ^ r;
	popFrame();
	return result;
}
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0) {
	NI result;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
	nimfr_("hashWangYi1", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(187);	nimln_(174);	T1_ = (NU64)0;
	T1_ = hiXorLo__pureZhashes_u80(11562461410679940143ULL, (NU64)(x_p0 ^ 16646288086500911323ULL));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(187);	T2_ = (NU64)0;
	T2_ = hiXorLo__pureZhashes_u80(T1_, 16952864883938283885ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("hash", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(216);	result = hashWangYi1__pureZhashes_u139(((NU64) (x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
	NIM_BOOL result;
	nimfr_("isFilled", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
	nimlf_(27, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");	result = !((hcode_p0 == ((NI)0)));
	popFrame();
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1) {
	NI result;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_4;
	nimfr_("nextTry", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{	result = (NI)0;
	nimln_(30);	if (nimAddInt(h_p0, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_4)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_4) & maxHash_p1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__vools95seq_u1042)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0, NI key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_5;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(72);	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u131(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_5)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_5);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__vools95seq_u1025)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w s_p0, NI key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("contains", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(169, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	hc_1 = 0;
	nimln_(170);	index_1 = rawGet__vools95seq_u1042(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(171);	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__vools95seq_u1183)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_8;
	NI T9_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_9;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!!((t_p0.counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u95(TM__0JXiWyhP5OCO8jWMA6sb1w_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = t_p0.data.len;
	if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))), &TM__0JXiWyhP5OCO8jWMA6sb1w_8)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_8));
	if (T6_) goto LA8_;
	T9_ = t_p0.data.len;
	if (nimSubInt(T9_, t_p0.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_9)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_9) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGetKnownHC__vools95seq_u1309)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w t_p0, NI key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_11;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(42);	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimln_(55);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimln_(55);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_11)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_11);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__vools95seq_u1366)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0, tySequence__8Np6tlClE5az1CyqZdN19bQ* data_p1, NI key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
	nimfr_("rawInsert", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(27, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym21__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym21__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(28);		if ((correctSizeX60gensym21__1) < ((NI)0) || (correctSizeX60gensym21__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym21__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__vools95seq_u871((&(*s_p0).data), (correctSizeX60gensym21__1));
	}
LA4_: ;
	nimln_(29);	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field1 = key_p2;
	nimln_(30);	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u951)(tySequence__8Np6tlClE5az1CyqZdN19bQ dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__vools95seq_u1257)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0) {
	tySequence__8Np6tlClE5az1CyqZdN19bQ n_1;
	NI T1_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_10;
	tySequence__8Np6tlClE5az1CyqZdN19bQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimln_(38);	T1_ = (*s_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__0JXiWyhP5OCO8jWMA6sb1w_10)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) < ((NI)0) || ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__vools95seq_u871((&n_1), ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_10)));
	nimln_(39);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(46, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		nimlf_(40, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		nimlf_(68, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(69);			while (1) {
				NI TM__0JXiWyhP5OCO8jWMA6sb1w_13;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(40, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");				i_1 = ((NI) (res_1));
				nimln_(41);				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_12;
					tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* T13_;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					nimln_(42);					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__vools95seq_u1309((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimSubInt(((NI)-1), T12_, &TM__0JXiWyhP5OCO8jWMA6sb1w_12)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_12);
					nimln_(43);					T13_ = (tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w*)0;
					T13_ = s_p0;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					rawInsert__vools95seq_u1366(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				nimlf_(74, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_13)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_13);
			} LA6: ;
		}
	}
	nimlf_(115, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	eqdestroy___vools95seq_u951(n_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, incl__vools95seq_u1130)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* s_p0, NI key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("incl", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(46, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym14__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym14__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(47);		if ((correctSizeX60gensym14__1) < ((NI)0) || (correctSizeX60gensym14__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym14__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__vools95seq_u871((&(*s_p0).data), (correctSizeX60gensym14__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	nimln_(49);	index_1 = rawGet__vools95seq_u1042((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(209, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	{
		tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* T15_;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_14;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_15;
		nimlf_(50, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");		if (!(index_1 < ((NI)0))) goto LA8_;
		nimln_(51);		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__vools95seq_u1183((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			nimln_(52);			enlarge__vools95seq_u1257(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(53);			index_1 = rawGetKnownHC__vools95seq_u1309((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		nimln_(54);		T15_ = (tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w*)0;
		T15_ = s_p0;
		if (nimSubInt(((NI)-1), index_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_14)) { raiseOverflow(); goto BeforeRet_;
		};
		rawInsert__vools95seq_u1366(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_14));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(55);		if (nimAddInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_15)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_15);
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u988)(tyObject_HashSet__9cGXCTjmb0s3dklxc5sed3w* dest_p0) {
	eqdestroy___vools95seq_u951((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u2360)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dest_p0.p->data[colontmp_].Field1.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u2400)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* dest_p0) {
	eqdestroy___vools95seq_u2360((*dest_p0).data);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vools95seq_u2315)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___vools95seq_u2312)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, init__vools95seq_u2221)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym31__1;
NIM_BOOL* nimErr_;
	nimfr_("init", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(19);	if ((initialSize_p1) < ((NI)0) || (initialSize_p1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(initialSize_p1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	correctSizeX60gensym31__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(23);	(*s_p0).counter = ((NI)0);
	nimlf_(115, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	if ((correctSizeX60gensym31__1) < ((NI)0) || (correctSizeX60gensym31__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym31__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__vools95seq_u2237((&(*s_p0).data), (correctSizeX60gensym31__1));
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A, initHashSet__vools95seq_u2207)(NI initialSize_p0) {
	tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A result;
NIM_BOOL* nimErr_;
	nimfr_("initHashSet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(134);	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A));
	nimln_(135);	init__vools95seq_u2221((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A, initSet__vools95seq_u2194)(NI initialSize_p0) {
	tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A result;
NIM_BOOL* nimErr_;
	nimfr_("initSet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A));
	nimln_(605);	result = initHashSet__vools95seq_u2207(initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1763)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
	nimfr_("eqStrings", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\strmantle.nim");
{	nimlf_(33, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\strmantle.nim");	result = NIM_FALSE;
	nimln_(34);	alen_1 = a_p0.len;
	nimln_(35);	blen_1 = b_p1.len;
	nimln_(36);	{
		if (!(alen_1 == blen_1)) goto LA3_;
		nimln_(37);		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			nimln_(32);			nimln_(37);			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		nimln_(38);		nimln_(32);		nimln_(38);		result = equalMem__system_u1763(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGet__vools95seq_u2455)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_16;
NIM_BOOL* nimErr_;
	nimfr_("rawGet", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(72, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");	nimln_(59);	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u586(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	nimln_(72);	{
		nimln_(60);		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		nimln_(72);		nimln_(64);		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	nimln_(42);	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		nimln_(43);		nimln_(75);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	nimln_(44);	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			nimln_(50);			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				nimln_(51);				nimln_(75);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			nimln_(52);			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_16)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_16);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__vools95seq_u2438)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A s_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("contains", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(169, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	hc_1 = 0;
	nimln_(170);	index_1 = rawGet__vools95seq_u2455(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(171);	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__vools95seq_u2596)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_18;
	NI T9_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_19;
NIM_BOOL* nimErr_;
	nimfr_("mustRehash", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(34, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!!((t_p0.counter < T3_))) goto LA4_;
		failedAssertImpl__stdZassertions_u95(TM__0JXiWyhP5OCO8jWMA6sb1w_17);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	nimln_(35);	T6_ = (NIM_BOOL)0;
	T7_ = t_p0.data.len;
	if (nimAddInt(t_p0.counter, (NI)((t_p0.counter) / (((NI)2))), &TM__0JXiWyhP5OCO8jWMA6sb1w_18)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = (T7_ < (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_18));
	if (T6_) goto LA8_;
	T9_ = t_p0.data.len;
	if (nimSubInt(T9_, t_p0.counter, &TM__0JXiWyhP5OCO8jWMA6sb1w_19)) { raiseOverflow(); goto BeforeRet_;
	};
	T6_ = ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_19) < ((NI)4));
LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, rawGetKnownHC__vools95seq_u2722)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_21;
NIM_BOOL* nimErr_;
	nimfr_("rawGetKnownHC", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\hashcommon.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(42);	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(43);		nimln_(55);		nimln_(43);		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(44);	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		nimln_(45);		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
			}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			nimln_(50);			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				if (h_1 < 0 || h_1 >= t_p0.data.len){ raiseIndexError2(h_1,t_p0.data.len-1); goto BeforeRet_;
				}
				T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				nimln_(51);				nimln_(55);				nimln_(51);				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			nimln_(52);			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	nimln_(53);	if (nimSubInt(((NI)-1), h_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_21)) { raiseOverflow(); goto BeforeRet_;
	};
	result = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_21);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__vools95seq_u2779)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
	nimfr_("rawInsert", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(27, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym43__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym43__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(28);		if ((correctSizeX60gensym43__1) < ((NI)0) || (correctSizeX60gensym43__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym43__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__vools95seq_u2237((&(*s_p0).data), (correctSizeX60gensym43__1));
	}
LA4_: ;
	nimlf_(1715, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system.nim");	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	eqcopy___system_u2723((&(*data_p1).p->data[h_p4].Field1), key_p2);
	nimlf_(30, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	if (h_p4 < 0 || h_p4 >= (*data_p1).len){ raiseIndexError2(h_p4,(*data_p1).len-1); goto BeforeRet_;
	}
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__vools95seq_u2670)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0) {
	tySequence__4eRCaZmrYLLw2k30GPTiMw n_1;
	NI T1_;
	NI TM__0JXiWyhP5OCO8jWMA6sb1w_20;
	tySequence__4eRCaZmrYLLw2k30GPTiMw T2_;
NIM_BOOL* nimErr_;
	nimfr_("enlarge", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimln_(38);	T1_ = (*s_p0).data.len;
	if (nimMulInt(T1_, ((NI)2), &TM__0JXiWyhP5OCO8jWMA6sb1w_20)) { raiseOverflow(); goto BeforeRet_;
	};
	if (((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_20)) < ((NI)0) || ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_20)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_20), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
	}
	newSeq__vools95seq_u2237((&n_1), ((NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_20)));
	nimln_(39);	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		nimlf_(46, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		nimlf_(40, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		nimlf_(68, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");		res_1 = ((NI)0);
		{
			nimln_(69);			while (1) {
				NI TM__0JXiWyhP5OCO8jWMA6sb1w_23;
				if (!(res_1 <= colontmp_)) goto LA6;
				nimlf_(40, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");				i_1 = ((NI) (res_1));
				nimln_(41);				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					NI TM__0JXiWyhP5OCO8jWMA6sb1w_22;
					tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* T13_;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					nimln_(42);					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__vools95seq_u2722((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimSubInt(((NI)-1), T12_, &TM__0JXiWyhP5OCO8jWMA6sb1w_22)) { raiseOverflow(); goto BeforeRet_;
					};
					j_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_22);
					nimln_(43);					T13_ = (tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A*)0;
					T13_ = s_p0;
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					if (i_1 < 0 || i_1 >= n_1.len){ raiseIndexError2(i_1,n_1.len-1); goto BeforeRet_;
					}
					rawInsert__vools95seq_u2779(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				nimlf_(74, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\iterators_1.nim");				if (nimAddInt(res_1, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_23)) { raiseOverflow(); goto BeforeRet_;
				};
				res_1 = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_23);
			} LA6: ;
		}
	}
	nimlf_(115, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	eqdestroy___vools95seq_u2360(n_1);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, incl__vools95seq_u2543)(tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* s_p0, NimStringV2 key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
	nimfr_("incl", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(46, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");	{
		NI T3_;
		NI correctSizeX60gensym36__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		nimln_(19);		correctSizeX60gensym36__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(23);		(*s_p0).counter = ((NI)0);
		nimln_(47);		if ((correctSizeX60gensym36__1) < ((NI)0) || (correctSizeX60gensym36__1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(correctSizeX60gensym36__1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		newSeq__vools95seq_u2237((&(*s_p0).data), (correctSizeX60gensym36__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	nimln_(49);	index_1 = rawGet__vools95seq_u2455((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(209, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\sets.nim");	{
		tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A* T15_;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_24;
		NI TM__0JXiWyhP5OCO8jWMA6sb1w_25;
		nimlf_(50, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\pure\\collections\\setimpl.nim");		if (!(index_1 < ((NI)0))) goto LA8_;
		nimln_(51);		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__vools95seq_u2596((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			nimln_(52);			enlarge__vools95seq_u2670(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(53);			index_1 = rawGetKnownHC__vools95seq_u2722((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		nimln_(54);		T15_ = (tyObject_HashSet__LzZqz6o9c3Op5kzUgaFRj1A*)0;
		T15_ = s_p0;
		if (nimSubInt(((NI)-1), index_1, &TM__0JXiWyhP5OCO8jWMA6sb1w_24)) { raiseOverflow(); goto BeforeRet_;
		};
		rawInsert__vools95seq_u2779(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_24));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(55);		if (nimAddInt((*s_p0).counter, ((NI)1), &TM__0JXiWyhP5OCO8jWMA6sb1w_25)) { raiseOverflow(); goto BeforeRet_;
		};
		(*s_p0).counter = (NI)(TM__0JXiWyhP5OCO8jWMA6sb1w_25);
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
}
