/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -IE:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@pstd@ssyncio.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@pstd@ssyncio.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <io.h>
#include <stdio.h>
#include <fcntl.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, atpstdatssynciodotnim_Init000)(void) {
{
	int T1_;
	int T2_;
	int T3_;
	nimfr_("syncio", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\std\\syncio.nim");
	nimlf_(834, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\std\\syncio.nim");	T1_ = (int)0;
	T1_ = _fileno(stdin);
	_setmode(T1_, _O_BINARY);
	nimln_(835);	T2_ = (int)0;
	T2_ = _fileno(stdout);
	_setmode(T2_, _O_BINARY);
	nimln_(836);	T3_ = (int)0;
	T3_ = _fileno(stderr);
	_setmode(T3_, _O_BINARY);
	nimTestErrorFlag();
	popFrame();
}
}

