/* Generated by Nim Compiler v2.2.10 */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -fno-strict-aliasing   -IE:\Dowloads\nim-2.2.10_x64\nim-2.2.10\lib -IE:\IDEProjects\AI\vools\nim_core -o e:\IDEProjects\AI\vools\nim_core\nimcache\@psystem@sexceptions.nim.c.o e:\IDEProjects\AI\vools\nim_core\nimcache\@psystem@sexceptions.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA;
typedef struct tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug;
typedef struct tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw;
typedef struct tyObject_ArithmeticDefect__kRhO9bNB5valDm4ml20zrew tyObject_ArithmeticDefect__kRhO9bNB5valDm4ml20zrew;
typedef struct tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__cjOqO0U2d5cxd8MvHBESIw tySequence__cjOqO0U2d5cxd8MvHBESIw;
typedef struct tySequence__cjOqO0U2d5cxd8MvHBESIw_Content tySequence__cjOqO0U2d5cxd8MvHBESIw_Content;
typedef struct tyObject_GcEnv__Z9bd9bQd9aDYgPXL4VzvgfUpA tyObject_GcEnv__Z9bd9bQd9aDYgPXL4VzvgfUpA;
typedef struct tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__b8r3R51XxIRG1m0qyOt5mw tyObject_CellSeq__b8r3R51XxIRG1m0qyOt5mw;
typedef struct tyTuple__nPRLgUjPdX6JfRJw4DXBrg tyTuple__nPRLgUjPdX6JfRJw4DXBrg;
typedef struct tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg;
typedef struct tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA;
typedef struct tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA;
typedef struct tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug {
	NI rc;
	NI rootIdx;
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__cjOqO0U2d5cxd8MvHBESIw {
  NI len; tySequence__cjOqO0U2d5cxd8MvHBESIw_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__cjOqO0U2d5cxd8MvHBESIw trace;
	Exception* up;
};
struct tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A {
	Exception Sup;
};
struct tyObject_ArithmeticDefect__kRhO9bNB5valDm4ml20zrew {
	tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A Sup;
};
struct tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw {
	tyObject_ArithmeticDefect__kRhO9bNB5valDm4ml20zrew Sup;
};
struct tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw {
	NI len;
	NI cap;
	tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__b8r3R51XxIRG1m0qyOt5mw {
	NI len;
	NI cap;
	tyTuple__nPRLgUjPdX6JfRJw4DXBrg* d;
};
struct tyObject_GcEnv__Z9bd9bQd9aDYgPXL4VzvgfUpA {
	tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw traceStack;
	tyObject_CellSeq__b8r3R51XxIRG1m0qyOt5mw toFree;
	NI freed;
	NI touched;
	NI edges;
	NI rcSum;
	NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
	void** Field0;
	TNimTypeV2* Field1;
};
struct tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA {
	tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A Sup;
};
struct tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg {
	tyObject_Defect__uQT66pli6T3pX9aAEQw8G7A Sup;
};
struct tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA {
	Exception Sup;
};
struct tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA {
	tyObject_CatchableError__lQVBR729cIs6ZefW5w1ZzDA Sup;
};
struct tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__cjOqO0U2d5cxd8MvHBESIw_Content { NI cap; tyObject_StackTraceEntry__ZTlQ0wXTVtPRAFw4DFml8g data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4592)(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA* dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4462)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_u3522)(NIM_BOOL isDestroyAction_p0, tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug* s_p1, TNimTypeV2* desc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5065)(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u3726)(tySequence__cjOqO0U2d5cxd8MvHBESIw dest_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5077)(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw* dest_p0, void* env_p1);
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1);
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw* s_p0, void** c_p1, TNimTypeV2* t_p2);
N_LIB_PRIVATE N_NIMCALL(void, resize__system_u3051)(tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw* s_p0);
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4604)(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4661)(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4673)(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg* dest_p0, void* env_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* dest_p0, void* env_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__5ufiG29cJAcQ9c7uYcBbREYA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__K7soRJaFO9b33BwEzz1ttNw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__9aohNscz9bzQg2lAXp89b4Ncg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_;
extern NIM_THREADVAR TFrame* framePtr__system_u2760;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4244;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[5] = {3701606400, 1285336064, 83552768, 407828480, 3139978240};
N_LIB_PRIVATE TNimTypeV2 NTIv2__K7soRJaFO9b33BwEzz1ttNw_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u58, .size = sizeof(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_u5077, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_3[4] = {3701606400, 1285336064, 83552768, 3890354944};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5ufiG29cJAcQ9c7uYcBbREYA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u56, .size = sizeof(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_3, .traceImpl = (void*)eqtrace___system_u4604, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_4[4] = {3701606400, 1285336064, 83552768, 2286792960};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9aohNscz9bzQg2lAXp89b4Ncg_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u62, .size = sizeof(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_4, .traceImpl = (void*)eqtrace___system_u4673, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_5[4] = {3701606400, 1285336064, 88164096, 2502841600};
N_LIB_PRIVATE TNimTypeV2 NTIv2__3ZUuVVw9cQ3EPL4rEijmGQA_ = {.destructor = (void*)rttiDestroy__systemZexceptions_u64, .size = sizeof(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), .align = (NI16) NIM_ALIGNOF(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_5, .traceImpl = (void*)eqtrace___pureZparseutils_u342, .flags = 0};
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2760 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2760).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2760;
	framePtr__system_u2760 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4462();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2760 = (*framePtr__system_u2760).prev;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("-%", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\arithmetics.nim");
	nimlf_(377, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\arithmetics.nim");	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) - (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u5065)(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3726((*dest_p0).Sup.Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.Sup.message.p && !((*dest_p0).Sup.Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.Sup.parent);
	}
LA9_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4244);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u58)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u5065(((tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, pluspercent___system_u793)(NI x_p0, NI y_p1) {
	NI result;
	nimfr_("+%", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\arithmetics.nim");
	nimln_(366);	result = ((NI) ((NU)((NU64)(((NU) (x_p0))) + (NU64)(((NU) (y_p1))))));
	popFrame();
	return result;
}
static N_INLINE(void, add__system_u3043)(tyObject_CellSeq__46f4noZBUV1owJ9cgjXF1Zw* s_p0, void** c_p1, TNimTypeV2* t_p2) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	nimfr_("add", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\cellseqs_v2.nim");
	nimlf_(28, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\cellseqs_v2.nim");	{
		if (!((*s_p0).cap <= (*s_p0).len)) goto LA3_;
		nimln_(29);		resize__system_u3051(s_p0);
	}
LA3_: ;
	nimln_(30);	colontmp_ = c_p1;
	colontmp__2 = t_p2;
	(*s_p0).d[(*s_p0).len].Field0 = colontmp_;
	(*s_p0).d[(*s_p0).len].Field1 = colontmp__2;
	nimln_(31);	(*s_p0).len = pluspercent___system_u793((*s_p0).len, ((NI)1));
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q_p0, void* env_p1) {
	void** p_1;
	nimfr_("nimTraceRefDyn", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\orc.nim");
	nimlf_(138, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\orc.nim");	p_1 = ((void**) (q_p0));
	nimln_(139);	{
		tyObject_GcEnv__Z9bd9bQd9aDYgPXL4VzvgfUpA* j_1;
		if (!!(((*p_1) == NIM_NIL))) goto LA3_;
		nimln_(140);		j_1 = ((tyObject_GcEnv__Z9bd9bQd9aDYgPXL4VzvgfUpA*) (env_p1));
		nimln_(141);		add__system_u3043((&(*j_1).traceStack), p_1, (*((TNimTypeV2**) ((*p_1)))));
	}
LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u5077)(tyObject_OverflowDefect__K7soRJaFO9b33BwEzz1ttNw* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.Sup.up, env_p1);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p_p0) {
	NIM_BOOL result;
	nimfr_("nimDecRefIsLastCyclicDyn", "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\orc.nim");
	nimln_(518);	result = NIM_FALSE;
	nimln_(519);	{
		tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		nimln_(520);		nimlf_(60, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\arc.nim");		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)16));
		cell_1 = ((tyObject_RefHeader__OX2KP9aEWv47TKGrINvU1ug*) (T5_));
		nimlf_(521, "E:\\Dowloads\\nim-2.2.10_x64\\nim-2.2.10\\lib\\system\\orc.nim");		{
			if (!((NI)((*cell_1).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			nimln_(522);			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			nimln_(525);			(*cell_1).rc = minuspercent___system_u813((*cell_1).rc, ((NI)16));
		}
LA6_: ;
		nimln_(527);		rememberCycle__system_u3522(result, cell_1, (*((TNimTypeV2**) (p_p0))));
	}
LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4592)(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3726((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u56)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4592(((tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4604)(tyObject_RangeDefect__5ufiG29cJAcQ9c7uYcBbREYA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_u4661)(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3726((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u62)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___system_u4661(((tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_u4673)(tyObject_IndexDefect__9aohNscz9bzQg2lAXp89b4Ncg* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparseutils_u330)(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.up);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.up);
	}
LA4_: ;
	eqdestroy___system_u3726((*dest_p0).Sup.Sup.trace);
	if ((*dest_p0).Sup.Sup.message.p && !((*dest_p0).Sup.Sup.message.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared((*dest_p0).Sup.Sup.message.p);
}
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest_p0).Sup.Sup.parent);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest_p0).Sup.Sup.parent);
	}
LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__systemZexceptions_u64)(void* dest_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___pureZparseutils_u330(((tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA*) (dest_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparseutils_u342)(tyObject_ValueError__3ZUuVVw9cQ3EPL4rEijmGQA* dest_p0, void* env_p1) {
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.parent, env_p1);
	nimTraceRefDyn(&(*dest_p0).Sup.Sup.up, env_p1);
}
